app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
//LOGIN
Route::resource('login', 'LoginController');
Route::get('/', 'LoginController@index');
//Logout seasson...
Route::get('logout', 'LoginController@logout');

//MAIN
Route::get('main', 'MainController@index');
Route::get('main/usuarios', 'MainController@usuarios');
Route::get('main/zonageo', 'MainController@zonageo');
Route::get('main/ausentismo', 'MainController@ausentismo');
Route::get('main/horarios', 'MainController@horarios');
Route::get('main/marcado', 'MainController@marcado');
//Recuperación PW
Route::get('main/cambiapw', 'MainController@cambiapw');
//Cambiar la contraseña
Route::post('main/pwreset', 'MainController@pwreset');

//USUARIOS
Route::resource('main/usuarios/administrar', 'UsuariosController');
Route::get('main/usuarios/nuevo','UsuariosController@nuevo');
Route::get('main/usuarios/export','UsuariosController@exportaUsuario');
Route::post('main/usuarios/administrar/borra','UsuariosController@delete');

//CELULARES
Route::resource('main/usuarios/administrarcel', 'CelularController');
Route::post('main/usuarios/administrarcel/borra','CelularController@delete');
Route::get('main/usuarios/celular','CelularController@celular');
Route::get('main/usuarios/exportcel','CelularController@exportaCelular');

//ZONAS GEOGRÁFICAS
Route::resource('main/zonageo/administrar', 'ZonaGeoController');
Route::resource('main/zonageo/asigadministrar', 'AsigZonaGeoController');
Route::post('main/zonageo/administrar/borra','ZonaGeoController@delete');
Route::post('main/zonageo/asigadministrar/borra','AsigZonaGeoController@delete');
Route::get('main/zonageo/nuevo','ZonaGeoController@nuevo');
Route::get('main/zonageo/asignuevo','AsigZonaGeoController@nuevo');
Route::get('main/zonageo/export','ZonaGeoController@exportaZonaGeo');
Route::get('main/zonageo/asigexport','AsigZonaGeoController@exportaZonaGeo');

//AUSENTISMO
Route::resource('main/ausentismo/administrar', 'AusentismoController');
Route::resource('main/ausentismo/asigadministrar', 'AsigAusentismoController');
Route::post('main/ausentismo/administrar/borra','AusentismoController@delete');
Route::post('main/ausentismo/asigadministrar/borra','AsigAusentismoController@delete');
Route::get('main/ausentismo/nuevo','AusentismoController@nuevo');
Route::get('main/ausentismo/asignuevo','AsigAusentismoController@nuevo');
Route::get('main/ausentismo/export','AusentismoController@exportaAusentismo');
Route::get('main/ausentismo/asigexport','AsigAusentismoController@exportaAusentismo');

//HORARIOS
Route::resource('main/horarios/administrar', 'HorariosController');
Route::resource('main/horarios/asigadministrar', 'AsigHorariosController');
Route::post('main/horarios/administrar/borra','HorariosController@delete');
Route::post('main/horarios/asigadministrar/borra','AsigHorariosController@delete');
Route::get('main/horarios/nuevo','HorariosController@nuevo');
Route::get('main/horarios/asignuevo','AsigHorariosController@nuevo');
Route::get('main/horarios/export','HorariosController@exportaHorario');
Route::get('main/horarios/asigexport','AsigHorariosController@exportaHorario');

//MARCAS Y CONSULTAS DE MARCAS
Route::resource('main/marcado/administrar', 'MarcadoController');
Route::get('main/marcado/marcau','MarcadoController@marcau');
Route::post('main/marcado/administrar/borra','MarcadoController@delete');
Route::get('main/marcado/reporte','MarcadoController1@reporte');
Route::get('main/marcado/export','MarcadoController@exportaMarcas');

app/Http/Controllers/HorariosController.php
<?php namespace Asistance\Http\Controllers;

use Asistance\Http\Requests;
use Asistance\Http\Controllers\Controller;

use Illuminate\Http\Request;

use Asistance\Http\Requests\HorariosRequest;
//Enlace a la ruta del modelo:
use Asistance\ModelHorarios;
//Para llamar a atributos reservados especiales:
use Illuminate\Support\Facades\Session; 
use Illuminate\Support\Facades\Redirect;
use DB;
use Maatwebsite\Excel\Facades\Excel;

class HorariosController extends Controller {

	/*Protegiendo las rutas asociadas a este controlador */
	public function __construct()
	{
		$this->middleware('auth');
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$horarios= ModelHorarios::orderBy('Alias_horario', 'DESC')
			->paginate(10);
		return view('sistema.horarios.administra',compact('horarios'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(HorariosRequest $request)
	{
		//Primera lógica de guardado: Buscar si el alias de usuario existe o no en el softdelete
		$logica=false;
		$comparadors=ModelHorarios::onlyTrashed()->get(); //sólo valores softdeleteados.
		foreach($comparadors as $comparador)
		{
			if($comparador->Alias_horario == $request->Alias_horario) //comparación)
			{
				$logica= true;
				break;
			}
		}
		//Segunda lógica: buscar el RUT en los valores normales no softdeleteados
		unset($comparadors); //limpieza de variable
		$comparadors=ModelHorarios::All();
		$logica2=false;
		foreach($comparadors as $comparador)
		{
			if($comparador->Alias_horario == $request->Alias_horario) //comparación)
			{
				$logica2= true;
				break;
			}
		}
		//Se compara logica, si es true significa que el alias ya fue empleado. hay que comparar la negación
		if($logica)
		{
			//Simplemente, se vuelve a validar el uso de ese usuario cuando hay registro previo y si hay registro de borrado en deleted_at
			ModelHorarios::withTrashed()-> where('Alias_horario', '=', $request->Alias_horario ) ->restore();
			Session::flash('message', 'No se genera nuevo horario, pero se habilita horario creado anteriormente.');
			return Redirect::to('main\horarios\nuevo');
		}
		//Se compara logica, si es false significa que el alias ya fue empleado.
		elseif(!$logica2)
		{
			//Corrección de los datos atrapados en el checkbox
			$request['Val_lunes'] = (! isset( $request['Val_lunes'] )) ? 0 : 1;
			$request['Val_Martes'] = (! isset( $request['Val_Martes'] )) ? 0 : 1;
			$request['Val_miercoles'] = (! isset( $request['Val_miercoles'] )) ? 0 : 1;
			$request['Val_jueves'] = (! isset( $request['Val_jueves'] )) ? 0 : 1;
			$request['Val_viernes'] = (! isset( $request['Val_viernes'] )) ? 0 : 1;
			$request['Val_sabado'] = (! isset( $request['Val_sabado'] )) ? 0 : 1;
			$request['Val_domingo'] = (! isset( $request['Val_domingo'] )) ? 0 : 1;

			ModelHorarios::create
			([
				'Alias_horario' =>$request['Alias_horario'],
				'Hora_inicio' => $request['Hora_inicio'],
				'Hora_final' => $request['Hora_final'],
				'Val_lunes' => $request['Val_lunes'],
				'Val_Martes' => $request['Val_Martes'],
				'Val_miercoles' => $request['Val_miercoles'],
				'Val_jueves' => $request['Val_jueves'],
				'Val_viernes' => $request['Val_viernes'],
				'Val_sabado' => $request['Val_sabado'],
				'Val_domingo' => $request['Val_domingo'],
			]);
				$request['Val_lunes'] = (! isset( $request['Val_lunes'] )) ? 0 : 1;
				Session::flash('message', 'Nuevo horario generado exitosamente');
				return Redirect::to('main/horarios/nuevo');
		}
		else
		{
			Session::flash('message', 'Horario no generado. Ya existe uno con el mismo nombre.');
			return Redirect::to('main/horarios/nuevo');
		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id, Request $request)
	{
		try
		{
			$Alias_horario=$request->get('Alias_horario');
			//Asignación a variable consulta de todos los elementos de la tabla de la relación "Horarios"			
			$horarios= ModelHorarios::orderBy('Alias_horario', 'DESC')
				->Alias_horario($Alias_horario)
				->paginate(10);
			//Retorno de la vista asociasa a edición de ausentismo
			return view('sistema.horarios.administra',compact('horarios'));
		}
		catch(\Exception $e)
		{
			Session::flash('message', 'Imposible filtrar. Dato en uso actualmente.');
			return Redirect::to('main\horarios\administrar');
		}
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$horario=ModelHorarios::find($id);
		return view('sistema.horarios.edit',['horario'=>$horario]);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id, HorariosRequest $request)
	{
			//Corrección de los datos atrapados en el checkbox
			$request['Val_lunes'] = (! isset( $request['Val_lunes'] )) ? 0 : 1;
			$request['Val_Martes'] = (! isset( $request['Val_Martes'] )) ? 0 : 1;
			$request['Val_miercoles'] = (! isset( $request['Val_miercoles'] )) ? 0 : 1;
			$request['Val_jueves'] = (! isset( $request['Val_jueves'] )) ? 0 : 1;
			$request['Val_viernes'] = (! isset( $request['Val_viernes'] )) ? 0 : 1;
			$request['Val_sabado'] = (! isset( $request['Val_sabado'] )) ? 0 : 1;
			$request['Val_domingo'] = (! isset( $request['Val_domingo'] )) ? 0 : 1;
			
			$horario=ModelHorarios::find($id);
			$horario->fill($request->all());
			$horario->save();
			Session::flash('message', 'Edición realizada exitosamente');
			return Redirect::to('main\horarios\administrar');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		try
		{
			//Antes de eliminar un horario, hay que asegurarse que éste no esté asignado a un trabajador
			$asignacion = DB::table('Usuario_Horario')->get();
			$logica = true;
			foreach($asignacion as $asigna)
			{
				if($asigna->id_horario == $id)
				{
					$logica = false;
					break;
				}
			}
			//$logica será verdadero en el caso que el horario no esté previamente asignado.
			if($logica)
			{
				$horario=ModelHorarios::find($id);
				$horario->delete();
				Session::flash('message', 'Eliminación realizada exitosamente');
				return Redirect::to('main\horarios\administrar');
			}
			else
			{
				Session::flash('message', 'Horario asignado a uno o varios usuarios. Desasignar antes de borrar.');
				return Redirect::to('main\horarios\administrar');
			}
			
		}
		catch(\Exception $e)
		{
			Session::flash('message', 'Imposible borrar. Dato en uso actualmente.');
			return Redirect::to('main\horarios\administrar');
		}
	}

    public function nuevo()
    {
        return view('sistema.horarios.nuevo');
    }

	public function delete(Request $request)
	{
		try
		{
			//Se recolecta en un arreglo, todas las ID a borrar
			$delets=$request->delete;
			//Evitar errores con un if... en caso que no existan checkboxs seleccionados es decir, no hay $delets
			if($delets)
			{	
				//Un primer foreach doble, para revisar que los delets elegidos no estén en uso.
				$asignacion = DB::table('Usuario_Horario')->get();
				$logica = true;	
				foreach($delets as $delet)
				{
					foreach($asignacion as $asigna)
					{
						if($asigna->id_horario == $delet)
						{
							$logica = false;
							break;
						}
					}
				}
				if($logica)
				{
					//Se recorre el arreglo $delets... para hacer el borrado
					foreach($delets as $delet)
					{
						$usuario=ModelHorarios::find($delet);
						$usuario->delete();
					}
					Session::flash('message', 'Eliminación masiva realizada exitosamente');
					return Redirect::to('main\horarios\administrar');
				}
				else
				{
					Session::flash('message', 'Uno o varios horarios seleccionados están asignados a uno o varios usuarios. Desasignar antes del borrado.');
					return Redirect::to('main\horarios\administrar');
				}				
			}
			else
			{
				Session::flash('message', 'No se han efectuado selecciones.');
				return Redirect::to('main\horarios\administrar');
			}
		}
		catch(\Exception $e)
		{
			Session::flash('message', 'Imposible borrar. Dato en uso actualmente.');
			return Redirect::to('main\horarios\administrar');
		}		 
	}

	public function exportaHorario()
	{
		Excel::create('Horario(Listado)', function($excel){
			$excel->sheet('Horario', function($sheet){
				$data = ModelHorarios::where('deleted_at', '=', null)
					->select('Alias_horario', 'Hora_inicio', 'Hora_final', 'Val_lunes', 
						'Val_Martes', 'Val_miercoles', 'Val_jueves', 'Val_viernes', 
						'Val_sabado', 'Val_domingo')
					->get(); 
				$sheet->fromArray($data);
			});
		})->download('xls');
		return back();
	}

}

resources/views/sistema/horarios/administra.blade.php
@extends('layouts.principal')

@section('bienvenida')
    <h1>Horario</h1>
    <p>Bienvenidos a Asistance</p>
    <p>Administración de horarios. Especificar operación</p>
    
	@include('alertas.alerta')
	@include('alertas.validaformulario')

    <!-- Buscar -->
    {!! Form::open(['route' => 'main.horarios.administrar.show', 'id'=>'cero','method' => 'GET'])!!}
    <div class="fields">
		<div class="field half">
        {!! Form::label('Alias_horario', 'Buscar por alias de horario: ') !!}
        {!! Form::text('Alias_horario', null, ['class' => 'form-control', 'maxlength' => '24', 'placeholder' =>'Ejemplo: HORARIO-0001']) !!}       
        </div>
	</div> 
    <p></p>
    {!! Form::submit('Mostrar resultados',['class' => 'button small']) !!}
    {!! Form::close()!!}
    <!-- Exportar Excel -->
    <a href="{{ url('main/horarios/export')}}" class="button submit">Exporta todos los Horarios *xls</a>
    <p></p>
    <!-- Tabla -->
    <h2>Tabla de Horarios</h2>
        {!! Form::open(['url' => 'main/horarios/administrar/borra', 'id'=>'uno','method' => 'post']) !!}        
        <p></p>
		<!--Tabla de ocurrencias de horarios -->
        <table class="table" size="small">
                <thead>
                    <th>Operación</th>
                    <th>Check</th>
                    <th>Alias Horario</th>
                    <th>Hora <br/>Inicial</th>
                    <th>Hora <br/>Final</th>
                    <th>L</th>
                    <th>M</th>
                    <th>Mi</th>
                    <th>J</th>
                    <th>V</th>
                    <th>S</th>
                    <th>D</th>
                </thead>
            @foreach($horarios as $horario) 
                <tbody>
                    <td>{!! link_to_route('main.horarios.administrar.edit', $title = 'Modificar', $parameters = $horario->id_horario , $attributes = ['class'=>'btn btn-primary']) !!}</td>
                    <td align="center"><input id="{{$horario->id_horario}}" value="{{$horario->id_horario}}" name="delete[]" type="checkbox" class="checkthis"/><label for="{{$horario->id_horario}}"></label></td>
                    <td>{{$horario->Alias_horario}}</td>
                    <td>{{$horario->Hora_inicio}}</td>
                    <td>{{$horario->Hora_final}}</td>
                    <td>                    
                        @if($horario->Val_lunes === 0)
                        No
                        @else
                        Sí     
                        @endif
                    </td>
                    <td>                    
                        @if($horario->Val_Martes === 0)
                        No
                        @else
                        Sí     
                        @endif
                    </td>
                    <td>                    
                        @if($horario->Val_miercoles === 0)
                        No
                        @else
                        Sí     
                        @endif
                    </td>
                    <td>                    
                        @if($horario->Val_jueves === 0)
                        No
                        @else
                        Sí     
                        @endif
                    </td>
                    <td>                    
                        @if($horario->Val_viernes === 0)
                        No
                        @else
                        Sí     
                        @endif
                    </td>
                    <td>                    
                        @if($horario->Val_sabado === 0)
                        No
                        @else
                        Sí     
                        @endif
                    </td>
                    <td>                    
                        @if($horario->Val_domingo === 0)
                        No
                        @else
                        Sí     
                        @endif
                    </td>
                </tbody>
            @endforeach
        </table>	
    {!! $horarios->render()!!}
    <p></p>
    <!-- Eliminación masiva -->
    {!! Form::submit('Eliminar check',['class' => 'button small']) !!}
    {!! Form::close()!!}
@stop            

@section('submenu')
@include('menus.horarios')
@stop           

@section('subseccion11')
@include('menus.menus_ayuda')
@stop    

resources/views/sistema/horarios/asigedit.blade.php
@extends('layouts.principal')

@section('bienvenida')
    <h1>Horario</h1>
    <p>Bienvenidos a Asistance</p>
    <p>Administración de asignación de horarios. Efectúe su edición</p>
    @include('alertas.alerta')
	@include('alertas.validaformulario')
    {!! Form::model($asighorario, ['route' => ['main.horarios.asigadministrar.update', $asighorario->contador], 'method' => 'PUT']) !!}
    <div class="fields">
        <div class="field half">
            {!! Form::label('RUT', 'RUT del trabajador: ') !!}
            {!! Form::text('RUT', null, ['class' => 'form-control', 'readonly'=>'readonly']) !!}
        </div>
        <div class="field half">
            {!! Form::label('Horario', 'Seleccione alias horario: ') !!}
            <select name="id_horario" id="id_horario" class="form-control" required="required">
                @foreach($horarios as $horario)
                    <option value="{{ $horario->id_horario}}" id="{{ $horario->id_horario}}" name="{{ $horario->id_horario}}">{{ $horario->Alias_horario }}</option>
                @endforeach
            </select>
        </div>
        <div class="field half">
            {!! Form::label('Fecha_inicio', 'Especifique fecha inicio del ausentismo: ') !!}
            {!! Form::date('Fecha_inicio', \Carbon\Carbon::now(), ['id' => 'datepicker','class' => 'form-control', 'placeholder' =>'Ejemplo: 30-03-2000', 'step'=>'1']) !!}
            </div>
        <div class="field half">
            {!! Form::label('Fecha_fin', 'Seleccionar fecha final del ausentismo: ') !!}
            {!! Form::date('Fecha_fin', \Carbon\Carbon::now(), ['id' => 'datepicker','class' => 'form-control', 'placeholder' =>'Ejemplo: 30-03-2000', 'step'=>'1']) !!}
        </div>
    </div>
    <ul class="actions">
    <li>
    {!! Form::submit('Actualizar',['class' => 'btn btn-primary']) !!}
    </li>
    </ul>
    {!! Form::close() !!}

    {!! Form::open(['route' => ['main.horarios.asigadministrar.destroy', $asighorario->contador], 'method' => 'DELETE']) !!}
        <ul class="actions">
    <li>{!! Form::submit('Eliminar',['class' => 'btn btn-danger']) !!}</li>
        </ul>
    {!! Form::close() !!}
@stop            

@section('submenu')
@include('menus.horarios')
@stop           

@section('subseccion11')
@include('menus.menus_ayuda')
@stop    

resources/views/sistema/horarios/asignar.blade.php
@extends('layouts.principal')

@section('bienvenida')
    <h1>Horario</h1>
    <p>Bienvenidos a Asistance</p>
    <p>Administración de asignación de horarios a trabajadores</p>
    
	@include('alertas.alerta')
	@include('alertas.validaformulario')
        <!-- Buscar -->
        <h4>Filtros de visualización (rangos respecto a fecha iniciales de horario)</h4>
        {!! Form::open(['route' => 'main.horarios.asigadministrar.show', 'method' => 'GET'])!!}
        <div class="fields">
            <div class="field half">
                {!! Form::label('RUT', 'Buscar por RUT: ') !!}
                <select name="RUT" id="RUT" class="form-control" required="required">
                    @foreach($usuarios as $usuario)
                        <option value="{{ $usuario->RUT}}" id="{{ $usuario->RUT}}" name="{{ $usuario->RUT}}">{{ $usuario->RUT}}: {{ $usuario->Apellido_P}} {{ $usuario->Apellido_M}} {{ $usuario->Nombres }}</option>
                    @endforeach
                </select>
            </div>
            <div class="field quarter">    
                {!! Form::label('fechaInicio', 'Buscar por fecha:  I') !!}         	
                {!! Form::date('fechaInicio', \Carbon\Carbon::now(), ['id' => 'datepicker','class' => 'form-control', 'placeholder' =>'Ejemplo: 30-03-2000', 'step'=>'1']) !!}
            </div>
            <div class="field quarter">    
                {!! Form::label('fechaFinal', 'Buscar por fecha: F ') !!}         	
                {!! Form::date('fechaFinal', \Carbon\Carbon::now(), ['id' => 'datepicker','class' => 'form-control', 'placeholder' =>'Ejemplo: 30-03-2000', 'step'=>'1']) !!}
            </div>
        </div>
        <p></p>
        {!! Form::submit('Mostrar resultados',['class' => 'button small']) !!}
        {!! Form::close()!!}
        <h4></h4>
        <!-- Exportar Excel -->
        <h4>Filtros de exportación tabla (rangos respecto a fecha iniciales de horario)</h4>
        {!! Form::open(['url' => 'main/horarios/asigexport', 'method' => 'GET']) !!}
        <div class="fields">
            <div class="field quarter">    
                {!! Form::label('fechaInicio', 'Fecha inicio: ') !!}         	
                {!! Form::date('fechaInicio', \Carbon\Carbon::now(), ['id' => 'datepicker','class' => 'form-control', 'placeholder' =>'Ejemplo: 30-03-2000', 'step'=>'1']) !!}
            </div>
            <div class="field quarter">    
                {!! Form::label('fechaFinal', 'Fecha fin: ') !!}         	
                {!! Form::date('fechaFinal', \Carbon\Carbon::now(), ['id' => 'datepicker','class' => 'form-control', 'placeholder' =>'Ejemplo: 30-03-2000', 'step'=>'1']) !!}
            </div>
        </div>
        <p></p>
        {!! Form::submit('Exporta todas las asignaciones de horarios *xls',['class' => 'button']) !!}
        {!! Form::close()!!}
        <p></p>
        <!-- Tabla -->
        <h2>Tabla de Asignación de Horarios</h2>        
        {!! Form::open(['url' => 'main/horarios/asigadministrar/borra', 'method' => 'post']) !!}              
        <p></p>
		<!--Tabla de ocurrencias de horarios -->
        <table class="table" align="center" id="tblData">
                <thead>
                    <th>Operación</th>
                    <th align="center">Check</th>
                    <th>RUT</th>
                    <th>Alias  <br/>horario</th>
                    <th>Fecha Inicial</th>
                    <th>Fecha Final</th>
                </thead>
            @foreach($asighorarios as $asighorario) 
                <tbody>
                    <td>{!! link_to_route('main.horarios.asigadministrar.edit', $title = 'Modificar', $parameters = $asighorario->contador, $attributes = ['class'=>'btn btn-primary']) !!}</td>
                    <td align="center"><input id="{{$asighorario->contador}}" value="{{$asighorario->contador}}" name="delete[]" type="checkbox" class="checkthis"/><label for="{{$asighorario->contador}}"></label></td>
                    <td>{{$asighorario->RUT}}</td>
                    <td>{{$asighorario->Alias_horario}}</td>
                    <td>{{ date('d-m-Y',strtotime($asighorario->Fecha_inicio)) }}</td>
                    <td>{{ date('d-m-Y',strtotime($asighorario->Fecha_fin))}}</td>
                </tbody>
            @endforeach
        </table>
    {!! $asighorarios->render()!!}	
    <p></p>
    <!-- Eliminación masiva -->
    {!! Form::submit('Eliminar check de asociaciones',['class' => 'button small']) !!}  
    {!! Form::close() !!}	

    
@stop            

@section('submenu')
@include('menus.horarios')
@stop             

@section('subseccion11')
@include('menus.menus_ayuda')
@stop    

resources/views/sistema/horarios/asignuevo.blade.php
@extends('layouts.principal')

@section('bienvenida')
    <h1>Horario</h1>
    <p>Bienvenidos a Asistance</p>
	<p>Nueva asignación de horario. Favor complete formulario</p>
	@include('alertas.alerta')
	@include('alertas.validaformulario')
	<section>
		<!--Formulario para crear una nueva asociación de horarios y ser almacenado a la BBDD -->
		{!! Form::open(['route' => 'main.horarios.asigadministrar.store', 'method' => 'POST']) !!}
			<div class="fields">
				<div class="field half">
					{!! Form::label('RUT', 'Seleccionar RUT del trabajador: ') !!}
                    <select name="RUT" id="RUT" class="form-control" required="required">
						@foreach($usuarios as $usuario)
							<option value="{{ $usuario->RUT}}" id="{{ $usuario->RUT}}" name="{{ $usuario->RUT}}">{{ $usuario->RUT}}: {{ $usuario->Apellido_P}} {{ $usuario->Apellido_M}} {{ $usuario->Nombres }}</option>
						@endforeach
					</select>
				</div>
				<div class="field half">
					{!! Form::label('Horario', 'Seleccione alias horario: ') !!}
					<select name="id_horario" id="id_horario" class="form-control" required="required">
						@foreach($horarios as $horario)
							<option value="{{ $horario->id_horario}}" id="{{ $horario->id_horario}}" name="{{ $horario->id_horario}}">{{ $horario->Alias_horario }}</option>
						@endforeach
					</select>
                </div>
                <div class="field half">
                    {!! Form::label('Fecha_inicio', 'Especifique fecha inicio del bloque horario: ') !!}
                    {!! Form::date('Fecha_inicio', \Carbon\Carbon::now(), ['id' => 'datepicker','class' => 'form-control', 'placeholder' =>'Ejemplo: 30-03-2000', 'step'=>'1']) !!}
                    </div>
                <div class="field half">
                    {!! Form::label('Fecha_fin', 'Seleccionar fecha final del bloque horario: ') !!}
                    {!! Form::date('Fecha_fin', \Carbon\Carbon::now(), ['id' => 'datepicker','class' => 'form-control', 'placeholder' =>'Ejemplo: 30-03-2000', 'step'=>'1']) !!}
                </div>
			</div>
			<ul class="actions">
				<li>
				{!! Form::submit('Generar nueva asociación',['class' => 'btn btn-primary']) !!}
				</li>
			</ul>
		{!! Form::close() !!}
	</section>	
@stop            

@section('submenu')
@include('menus.horarios')
@stop           

@section('subseccion11')
@include('menus.menus_ayuda')
@stop       