app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
//LOGIN
Route::resource('login', 'LoginController');
Route::get('/', 'LoginController@index');
//Logout seasson...
Route::get('logout', 'LoginController@logout');

//MAIN
Route::get('main', 'MainController@index');
Route::get('main/usuarios', 'MainController@usuarios');
Route::get('main/zonageo', 'MainController@zonageo');
Route::get('main/ausentismo', 'MainController@ausentismo');
Route::get('main/horarios', 'MainController@horarios');
Route::get('main/marcado', 'MainController@marcado');
//Recuperación PW
Route::get('main/cambiapw', 'MainController@cambiapw');
//Cambiar la contraseña
Route::post('main/pwreset', 'MainController@pwreset');

//USUARIOS
Route::resource('main/usuarios/administrar', 'UsuariosController');
Route::get('main/usuarios/nuevo','UsuariosController@nuevo');
Route::get('main/usuarios/export','UsuariosController@exportaUsuario');
Route::post('main/usuarios/administrar/borra','UsuariosController@delete');

//CELULARES
Route::resource('main/usuarios/administrarcel', 'CelularController');
Route::post('main/usuarios/administrarcel/borra','CelularController@delete');
Route::get('main/usuarios/celular','CelularController@celular');
Route::get('main/usuarios/exportcel','CelularController@exportaCelular');

//ZONAS GEOGRÁFICAS
Route::resource('main/zonageo/administrar', 'ZonaGeoController');
Route::resource('main/zonageo/asigadministrar', 'AsigZonaGeoController');
Route::post('main/zonageo/administrar/borra','ZonaGeoController@delete');
Route::post('main/zonageo/asigadministrar/borra','AsigZonaGeoController@delete');
Route::get('main/zonageo/nuevo','ZonaGeoController@nuevo');
Route::get('main/zonageo/asignuevo','AsigZonaGeoController@nuevo');
Route::get('main/zonageo/export','ZonaGeoController@exportaZonaGeo');
Route::get('main/zonageo/asigexport','AsigZonaGeoController@exportaZonaGeo');

//AUSENTISMO
Route::resource('main/ausentismo/administrar', 'AusentismoController');
Route::resource('main/ausentismo/asigadministrar', 'AsigAusentismoController');
Route::post('main/ausentismo/administrar/borra','AusentismoController@delete');
Route::post('main/ausentismo/asigadministrar/borra','AsigAusentismoController@delete');
Route::get('main/ausentismo/nuevo','AusentismoController@nuevo');
Route::get('main/ausentismo/asignuevo','AsigAusentismoController@nuevo');
Route::get('main/ausentismo/export','AusentismoController@exportaAusentismo');
Route::get('main/ausentismo/asigexport','AsigAusentismoController@exportaAusentismo');

//HORARIOS
Route::resource('main/horarios/administrar', 'HorariosController');
Route::resource('main/horarios/asigadministrar', 'AsigHorariosController');
Route::post('main/horarios/administrar/borra','HorariosController@delete');
Route::post('main/horarios/asigadministrar/borra','AsigHorariosController@delete');
Route::get('main/horarios/nuevo','HorariosController@nuevo');
Route::get('main/horarios/asignuevo','AsigHorariosController@nuevo');
Route::get('main/horarios/export','HorariosController@exportaHorario');
Route::get('main/horarios/asigexport','AsigHorariosController@exportaHorario');

//MARCAS Y CONSULTAS DE MARCAS
Route::resource('main/marcado/administrar', 'MarcadoController');
Route::get('main/marcado/marcau','MarcadoController@marcau');
Route::post('main/marcado/administrar/borra','MarcadoController@delete');
Route::get('main/marcado/reporte','MarcadoController1@reporte');
Route::get('main/marcado/export','MarcadoController@exportaMarcas');

app/Http/Controllers/AusentismoController.php
<?php namespace Asistance\Http\Controllers;

use Asistance\Http\Requests;
use Asistance\Http\Controllers\Controller;

use Illuminate\Http\Request;

//Enlace a la ruta del modelo:
use Asistance\ModelAusentismo;
//ENlazando el request
use Asistance\Http\Requests\AusentismoRequest;
//Para llamar a atributos reservados especiales:
use Illuminate\Support\Facades\Session; 
use Illuminate\Support\Facades\Redirect;
use DB;
use Maatwebsite\Excel\Facades\Excel;

class AusentismoController extends Controller {

	/*Protegiendo las rutas asociadas a este controlador */
	public function __construct()
	{
		$this->middleware('auth');
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$ausentismos= ModelAusentismo::orderBy('Nombre_AusentismoFestivo', 'DESC')
			->paginate(10);
        return view('sistema.ausentismo.administra',compact('ausentismos'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(AusentismoRequest $request)
	{
		//Primera lógica de guardado: Buscar si el alias de ausentismo existe o no en el softdelete
		$logica=false;
		$comparadors=ModelAusentismo::onlyTrashed()->get(); //sólo valores softdeleteados.
		foreach($comparadors as $comparador)
		{
			if($comparador->Nombre_AusentismoFestivo == $request->Nombre_AusentismoFestivo) //comparación)
			{
				$logica= true;
				break;
			}
		}
		//Segunda lógica: buscar el nombre del ausentismo en los valores normales no softdeleteados
		unset($comparadors); //limpieza de variable
		$comparadors=ModelAusentismo::All();
		$logica2=false;
		foreach($comparadors as $comparador)
		{
			if($comparador->Nombre_AusentismoFestivo == $request->Nombre_AusentismoFestivo) //comparación)
			{
				$logica2= true;
				break;
			}
		}
		//Se compara logica, si es true significa que el alias ya fue empleado. hay que comparar la negación
		if($logica)
		{
			//Simplemente, se vuelve a validar el uso de ese usuario cuando hay registro previo y si hay registro de borrado en deleted_at
			ModelAusentismo::withTrashed()-> where('Nombre_AusentismoFestivo', '=', $request->Nombre_AusentismoFestivo ) ->restore();
			Session::flash('message', 'No se genera nuevo ausentismo, pero se habilita ausentismo creado anteriormente.');
			return Redirect::to('main\ausentismo\nuevo');
		}
		//Se compara logica, si es false significa que el alias ya fue empleado.
		elseif(!$logica2)
		{
			ModelAusentismo::create
			([
				'Nombre_AusentismoFestivo' =>$request['Nombre_AusentismoFestivo'],
				'pago' => $request['pago'],
			]);
			Session::flash('message', 'Nuevo ausentismo generado exitosamente');
			return Redirect::to('main/ausentismo/nuevo');
		}
		else
		{
			Session::flash('message', 'No se genera nuevo ausentismo, ya existe uno del mismo nombre');
			return Redirect::to('main/ausentismo/nuevo');
		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id, Request $request)
	{
		try
		{
			$Nombre_AusentismoFestivo=$request->get('Nombre_AusentismoFestivo');
			//Asignación a variable consulta de todos los elementos de la tabla de la relación "Ausentismo"
			$ausentismos=ModelAusentismo::orderBy('Nombre_AusentismoFestivo', 'DESC')
				->Nombre_AusentismoFestivo($Nombre_AusentismoFestivo)
				->paginate(10);
			//Retorno de la vista asociasa a edición de ausentismo
			return view('sistema.ausentismo.administra',compact('ausentismos'));
		}
		catch(\Exception $e)
		{
			Session::flash('message', 'Imposible filtrar. Dato en uso actualmente.');
			return Redirect::to('main\ausentismo\administrar');
		}
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$ausentismo=ModelAusentismo::find($id);
		return view('sistema.ausentismo.edit',['ausentismo'=>$ausentismo]);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id, AusentismoRequest $request)
	{
		$ausentismo=ModelAusentismo::find($id);
		$ausentismo->fill($request->all());
		$ausentismo->save();
		Session::flash('message', 'Edición realizada exitosamente');
		return Redirect::to('main\ausentismo\administrar');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		try
		{
			//Antes de eliminar un ausentismo, hay que asegurarse que el número no esté asignado a un trabajador
			$asignacion = DB::table('Calendario_AusenFeriado')->get();
			$logica = true;
			foreach($asignacion as $asigna)
			{
				if($asigna->id_ausen_fest == $id)
				{
					$logica = false;
					break;
				}
			}
			//$logica será verdadero en el caso que el ausentismo no esté previamente asignado.
			if($logica)
			{
				//Notar que este método no eliminará nada sino que ocultará regstros.
				$ausentismo=ModelAusentismo::find($id);
				$ausentismo->delete();
				Session::flash('message', 'Eliminación realizada exitosamente');
				return Redirect::to('main\ausentismo\administrar');
			}
			else
			{
				Session::flash('message', 'Ausentismo asignado a uno o varios usuarios. Desasignar antes de borrar.');
				return Redirect::to('main\ausentismo\administrar');
			}
		}
		catch(\Exception $e)
		{
			Session::flash('message', 'Imposible borrar. Ausentismo en uso actualmente.');
			return Redirect::to('main\ausentismo\administrar');
		}
	}

	public function nuevo()
    {
		//Para nuevos registros
        return view('sistema.ausentismo.nuevo');
    }

	public function delete(Request $request)
	{
		try
		{
			//Se recolecta en un arreglo, todas las ID a borrar
			$delets=$request->delete;
			//Evitar errores con un if... en caso que no existan checkboxs seleccionados es decir, no hay $delets
			if($delets)
			{	
				//Un primer foreach doble, para revisar que los delets elegidos no estén en uso.
				$asignacion = DB::table('Calendario_AusenFeriado')->get();
				$logica = true;	
				foreach($delets as $delet)
				{
					foreach($asignacion as $asigna)
					{
						if($asigna->id_ausen_fest == $delet)
						{
							$logica = false;
							break;
						}
					}
				}
				if($logica)
				{
					//Se recorre el arreglo $delets... para hacer el borrado
					foreach($delets as $delet)
					{
						$ausentismo=ModelAusentismo::find($delet);
						$ausentismo->delete();
					}
					Session::flash('message', 'Eliminación masiva realizada exitosamente');
					return Redirect::to('main\ausentismo\administrar');
				}
				else
				{
					Session::flash('message', 'Uno o varios de los ausentismos asignados a uno o varios usuarios. Desasignar antes de borrar.');
					return Redirect::to('main\ausentismo\administrar');
				}
			}
			else
			{
				Session::flash('message', 'No se han efectuado selecciones.');
				return Redirect::to('main\ausentismo\administrar');
			}
		}
		catch(\Exception $e)
		{
			Session::flash('message', 'Imposible borrar. Ausentismo(s) en uso actualmente.');
			return Redirect::to('main\ausentismo\administrar');
		}
		
	}

	public function exportaAusentismo()
	{
		Excel::create('Ausentismo(Listado)', function($excel){
			$excel->sheet('Ausentismo', function($sheet){
				$data = ModelAusentismo::where('deleted_at', '=', null)
					->select('Nombre_AusentismoFestivo', 'pago')
					->get(); 
				$sheet->fromArray($data);
				$sheet->cell('B1', function($cell) { $cell->setValue('¿Ausentismo Remunerado?'); });
			});
		})->download('xls');
		return back();
	}
}

resources/views/sistema/ausentismo/administra.blade.php
@extends('layouts.principal')

@section('bienvenida')
    <h1>Ausentismo</h1>
    <p>Bienvenidos a Asistance</p>
    <p>Administración de ausentismos. Especificar operación</p>
   
	@include('alertas.alerta')
	@include('alertas.validaformulario')

    <!-- Buscar -->
    {!! Form::open(['route' => 'main.ausentismo.administrar.show', 'method' => 'GET'])!!}
    <div class="fields">
		<div class="field half">
            {!! Form::label('Nombre_AusentismoFestivo', 'Buscas por alias de ausentismo: ') !!}
            {!! Form::text('Nombre_AusentismoFestivo', null, ['class' => 'form-control', 'maxlength' => '24', 'placeholder' =>'Ejemplo: Vacación']) !!}   
        </div>
	</div>    
    <p></p>
    {!! Form::submit('Mostrar resultados',['class' => 'button small']) !!}
    {!! Form::close()!!}
    <!-- Exportar Excel -->
    <a href="{{ url('main/ausentismo/export')}}" class="button submit">Exporta todos los Ausentismos *xls</a>
    <p></p>
    <!-- Tabla -->
    <h2>Tabla de Ausentismos</h2>
        {!! Form::open(['url' => 'main/ausentismo/administrar/borra', 'method' => 'post']) !!}
        <p></p>
        <table class="table" align="center" size="small">
                <thead>
                    <th>Operación</th>
                    <th align="center">Check</th>
                    <th>Ausentismo</th>
                    <th>Validador de <br/>remuneración</th>
                </thead>
            @foreach($ausentismos as $ausentismo) 
                <tbody>
                    <td>{!! link_to_route('main.ausentismo.administrar.edit', $title = 'Modificar', $parameters = $ausentismo->id_ausen_fest , $attributes = ['class'=>'btn btn-primary']) !!}</td>
                    <td align="center"><input id="{{$ausentismo->id_ausen_fest}}" value="{{$ausentismo->id_ausen_fest}}" name="delete[]" type="checkbox" class="checkthis"/><label for="{{$ausentismo->id_ausen_fest}}"></label></td>
                    <td>{{$ausentismo->Nombre_AusentismoFestivo}}</td>
                    <td>                        
                        @if($ausentismo->pago === 0)
                        No
                        @else
                        Sí     
                        @endif
                    </td>
                </tbody>
            @endforeach
        </table>
    {!! $ausentismos->render()!!}
    <p></p>
    <!-- Eliminación masiva -->
    {!! Form::submit('Eliminar check',['class' => 'button small']) !!}
    {!! Form::close() !!}
@stop            

@section('submenu')
@include('menus.ausentismo')
@stop           

@section('subseccion11')
@include('menus.menus_ayuda')
@stop    

resources/views/sistema/ausentismo/asigedit.blade.php
@extends('layouts.principal')

@section('bienvenida')
    <h1>Ausentismo</h1>
    <p>Bienvenidos a Asistance</p>
    <p>Administración de asignación de ausentismos. Efectúe su edición</p>
    @include('alertas.alerta')
	@include('alertas.validaformulario')
    {!! Form::model($asigausentismo, ['route' => ['main.ausentismo.asigadministrar.update', $asigausentismo->contador], 'method' => 'PUT']) !!}
    <div class="fields">
        <div class="field half">
            {!! Form::label('RUT', 'RUT del trabajador: ') !!}
            {!! Form::text('RUT', null, ['class' => 'form-control', 'readonly'=>'readonly']) !!}
        </div>
        <div class="field half">
            {!! Form::label('Ausentismo', 'Seleccione ausentismo: ') !!}
            <select name="id_ausen_fest" id="id_ausen_fest" class="form-control" required="required">
                @foreach($ausentismos as $ausentismo)
                    <option value="{{ $ausentismo->id_ausen_fest}}" id="{{ $ausentismo->id_ausen_fest}}" name="{{ $ausentismo->id_ausen_fest}}">{{ $ausentismo->Nombre_AusentismoFestivo }}</option>
                @endforeach
            </select>
        </div>
        <div class="field half">
            {!! Form::label('Fecha_inicio', 'Especifique fecha inicio del ausentismo: ') !!}
            {!! Form::date('Fecha_inicio', \Carbon\Carbon::now(), ['id' => 'datepicker','class' => 'form-control', 'placeholder' =>'Ejemplo: 30-03-2000', 'step'=>'1']) !!}
            </div>
        <div class="field half">
            {!! Form::label('Fecha_fin', 'Seleccionar fecha final del ausentismo: ') !!}
            {!! Form::date('Fecha_fin', \Carbon\Carbon::now(), ['id' => 'datepicker','class' => 'form-control', 'placeholder' =>'Ejemplo: 30-03-2000', 'step'=>'1']) !!}
        </div>
    </div>
    <ul class="actions">
    <li>
    {!! Form::submit('Actualizar',['class' => 'btn btn-primary']) !!}
    </li>
    </ul>
    {!! Form::close() !!}

    {!! Form::open(['route' => ['main.ausentismo.asigadministrar.destroy', $asigausentismo->contador], 'method' => 'DELETE']) !!}
        <ul class="actions">
    <li>{!! Form::submit('Eliminar',['class' => 'btn btn-danger']) !!}</li>
        </ul>
    {!! Form::close() !!}
@stop            

@section('submenu')
@include('menus.ausentismo')
@stop           

@section('subseccion11')
@include('menus.menus_ayuda')
@stop    

resources/views/sistema/ausentismo/asignar.blade.php
@extends('layouts.principal')

@section('bienvenida')
    <h1>Ausentismo</h1>
    <p>Bienvenidos a Asistance</p>
    <p>Administración de ausentismos. Asignación de ausentismos a trabajadores</p>
    
	@include('alertas.alerta')
	@include('alertas.validaformulario')
        <!-- Buscar -->
        <h4>Filtros de exportación tabla (rangos de fecha respecto a fecha asignación inicial)</h4>
        {!! Form::open(['route' => 'main.ausentismo.asigadministrar.show', 'method' => 'GET'])!!}
        <div class="fields">
            <div class="field half">
                {!! Form::label('RUT', 'Buscar por RUT: ') !!}
                <select name="RUT" id="RUT" class="form-control" required="required">
                    @foreach($usuarios as $usuario)
                        <option value="{{ $usuario->RUT}}" id="{{ $usuario->RUT}}" name="{{ $usuario->RUT}}">{{ $usuario->RUT}}: {{ $usuario->Apellido_P}} {{ $usuario->Apellido_M}} {{ $usuario->Nombres }}</option>
                    @endforeach
                </select>
                </div>
            <div class="field quarter">    
                {!! Form::label('fechaInicio', 'Buscar por fecha:  I') !!}         	
                {!! Form::date('fechaInicio', \Carbon\Carbon::now(), ['id' => 'datepicker','class' => 'form-control', 'placeholder' =>'Ejemplo: 30-03-2000', 'step'=>'1']) !!}
            </div>
            <div class="field quarter">    
                {!! Form::label('fechaFinal', 'Buscar por fecha: F ') !!}         	
                {!! Form::date('fechaFinal', \Carbon\Carbon::now(), ['id' => 'datepicker','class' => 'form-control', 'placeholder' =>'Ejemplo: 30-03-2000', 'step'=>'1']) !!}
            </div>
        </div>
        <p></p>
        {!! Form::submit('Mostrar resultados',['class' => 'button small']) !!}
        {!! Form::close()!!}
        <h4></h4>
        <!-- Exportar Excel -->
        <h4>Filtros de exportación tabla (rangos de fecha respecto a fecha asignación inicial)</h4>
        {!! Form::open(['url' => 'main/ausentismo/asigexport', 'method' => 'GET']) !!}
        <div class="fields">
            <div class="field quarter">    
                {!! Form::label('fechaInicio', 'Fecha inicio: ') !!}         	
                {!! Form::date('fechaInicio', \Carbon\Carbon::now(), ['id' => 'datepicker','class' => 'form-control', 'placeholder' =>'Ejemplo: 30-03-2000', 'step'=>'1']) !!}
            </div>
            <div class="field quarter">    
                {!! Form::label('fechaFinal', 'Fecha fin: ') !!}         	
                {!! Form::date('fechaFinal', \Carbon\Carbon::now(), ['id' => 'datepicker','class' => 'form-control', 'placeholder' =>'Ejemplo: 30-03-2000', 'step'=>'1']) !!}
            </div>
        </div>
        <p></p>
        {!! Form::submit('Exporta todas las asignaciones de ausentismos *xls',['class' => 'button']) !!}
        {!! Form::close()!!}
        <p></p>
        <!-- Tabla -->
        <h2>Tabla de Asignación Ausentismo</h2>
        {!! Form::open(['url' => 'main/ausentismo/asigadministrar/borra', 'method' => 'post']) !!}   
        <p></p>
        <!--Tabla de ocurrencias de ausentismos -->
        <table class="table" align="center" id="tblData">
                <thead>
                    <th>Operación</th>
                    <th align="center">Check</th>
                    <th>RUT</th>
                    <th>Tipo  <br/>ausentismo</th>
                    <th>Fecha Inicial</th>
                    <th>Fecha Final</th>
                </thead>
            @foreach($asigausentismos as $asigausentismo) 
                <tbody>
                    <td>{!! link_to_route('main.ausentismo.asigadministrar.edit', $title = 'Modificar', $parameters = $asigausentismo->contador, $attributes = ['class'=>'btn btn-primary']) !!}</td>
                    <td align="center"><input id="{{$asigausentismo->contador}}" value="{{$asigausentismo->contador}}" name="delete[]" type="checkbox" class="checkthis"/><label for="{{$asigausentismo->contador}}"></label></td>
                    <td>{{$asigausentismo->RUT}}</td>
                    <td>{{$asigausentismo->Nombre_AusentismoFestivo}}</td>
                    <td>{{ date('d-m-Y',strtotime($asigausentismo->Fecha_inicio))  }}</td>
                    <td>{{ date('d-m-Y',strtotime($asigausentismo->Fecha_fin))  }}</td>
                </tbody>
            @endforeach
        </table>
    {!! $asigausentismos->render()!!}
    <p></p>
    <!-- Eliminación masiva -->
    {!! Form::submit('Eliminar check de asociaciones',['class' => 'button small']) !!}
    {!! Form::close() !!}		
    
@stop            

@section('submenu')
@include('menus.ausentismo')
@stop           

@section('subseccion11')
@include('menus.menus_ayuda')
@stop    

resources/views/sistema/ausentismo/asignuevo.blade.php
@extends('layouts.principal')

@section('bienvenida')
    <h1>Ausentismo</h1>
    <p>Bienvenidos a Asistance</p>
	<p>Nueva asignación de ausentismo. Favor complete formulario</p>
	@include('alertas.alerta')
	@include('alertas.validaformulario')
	<section>
		<!--Formulario para crear una nueva asociación de ausentismo y ser almacenado a la BBDD -->
		{!! Form::open(['route' => 'main.ausentismo.asigadministrar.store', 'method' => 'POST']) !!}
			<div class="fields">
				<div class="field half">
					{!! Form::label('RUT', 'Seleccionar RUT del trabajador: ') !!}
                    <select name="RUT" id="RUT" class="form-control" required="required">
						@foreach($usuarios as $usuario)
							<option value="{{ $usuario->RUT}}" id="{{ $usuario->RUT}}" name="{{ $usuario->RUT}}">{{ $usuario->RUT}}: {{ $usuario->Apellido_P}} {{ $usuario->Apellido_M}} {{ $usuario->Nombres }}</option>
						@endforeach
					</select>
				</div>
				<div class="field half">
					{!! Form::label('Ausentismo', 'Seleccione ausentismo: ') !!}
					<select name="id_ausen_fest" id="id_ausen_fest" class="form-control" required="required">
						@foreach($ausentismos as $ausentismo)
							<option value="{{ $ausentismo->id_ausen_fest}}" id="{{ $ausentismo->id_ausen_fest}}" name="{{ $ausentismo->id_ausen_fest}}">{{ $ausentismo->Nombre_AusentismoFestivo }}</option>
						@endforeach
					</select>
                </div>
                <div class="field half">
                    {!! Form::label('Fecha_inicio', 'Especifique fecha inicio del ausentismo: ') !!}
                    {!! Form::date('Fecha_inicio', \Carbon\Carbon::now(), ['id' => 'datepicker','class' => 'form-control', 'placeholder' =>'Ejemplo: 30-03-2000', 'step'=>'1']) !!}
                    </div>
                <div class="field half">
                    {!! Form::label('Fecha_fin', 'Seleccionar fecha final del ausentismo: ') !!}
                    {!! Form::date('Fecha_fin', \Carbon\Carbon::now(), ['id' => 'datepicker','class' => 'form-control', 'placeholder' =>'Ejemplo: 30-03-2000', 'step'=>'1']) !!}
                </div>
			</div>
			<ul class="actions">
				<li>
				{!! Form::submit('Generar nueva asociación',['class' => 'btn btn-primary']) !!}
				</li>
			</ul>
		{!! Form::close() !!}
	</section>	
@stop            

@section('submenu')
@include('menus.ausentismo')
@stop           

@section('subseccion11')
@include('menus.menus_ayuda')
@stop       

resources/views/sistema/ausentismo/edit.blade.php
@extends('layouts.principal')

@section('bienvenida')
    <h1>Ausentismo</h1>
    <p>Bienvenidos a Asistance</p>
    <p>Administración de ausentismos. Efectúe su edición</p>
    @include('alertas.alerta')
	@include('alertas.validaformulario')
    {!! Form::model($ausentismo, ['route' => ['main.ausentismo.administrar.update', $ausentismo->id_ausen_fest], 'method' => 'PUT']) !!}
        <div class="fields">
            <div class="field half">            
                {!! Form::label('Nombre_AusentismoFestivo', 'Alias del ausentismo a actualizar: ') !!}
                {!! Form::text('Nombre_AusentismoFestivo', null, ['class' => 'form-control', 'readonly'=>'readonly']) !!}
            </div>
            <div class="field half">
                {!! Form::label('pago', '¿Ausentismo remunerado?: ') !!}
                {!!	Form::select('pago', ['1' => 'Sí', '0' => 'No'], '1') !!}
            </div>
        </div>
    <ul class="actions">
    <li>
    {!! Form::submit('Actualizar',['class' => 'btn btn-primary']) !!}
    </li>
    </ul>
    {!! Form::close() !!}

    {!! Form::open(['route' => ['main.ausentismo.administrar.destroy', $ausentismo->id_ausen_fest], 'method' => 'DELETE']) !!}
        <ul class="actions">
    <li>{!! Form::submit('Eliminar',['class' => 'btn btn-danger']) !!}</li>
        </ul>
    {!! Form::close() !!}
@stop            

@section('submenu')
@include('menus.ausentismo')
@stop           

@section('subseccion11')
@include('menus.menus_ayuda')
@stop    

resources/views/sistema/ausentismo/nuevo.blade.php
@extends('layouts.principal')

@section('bienvenida')
    <h1>Ausentismo</h1>
    <p>Bienvenidos a Asistance</p>
	<p>Nuevo ausentismo. Favor complete formulario</p>
	@include('alertas.alerta')
	@include('alertas.validaformulario')
	<section>
		<!--Formulario para crear un nuevo ausentismo y ser almacenado a la BBDD -->
		{!! Form::open(['route' => 'main.ausentismo.administrar.store', 'method' => 'POST']) !!}
			<div class="fields">
				<div class="field half">
					{!! Form::label('Nombre_AusentismoFestivo', 'Alias o pseudónimo: ') !!}
					{!! Form::text('Nombre_AusentismoFestivo', null, ['class' => 'form-control', 'maxlength' => '24', 'placeholder' =>'Ejemplo: Vacación']) !!}
				</div>
				<div class="field half">
					{!! Form::label('pago', '¿Ausentismo remunerado?: ') !!}
					{!!	Form::select('pago', ['1' => 'Sí', '0' => 'No'], '1') !!}
				</div>
			</div>
			<ul class="actions">
				<li>
				{!! Form::submit('Generar nuevo ausentismo',['class' => 'btn btn-primary']) !!}
				</li>
			</ul>
		{!! Form::close() !!}
	</section>	
@stop            

@section('submenu')
@include('menus.ausentismo')
@stop           

@section('subseccion11')
@include('menus.menus_ayuda')
@stop       