app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
//LOGIN
Route::resource('login', 'LoginController');
Route::get('/', 'LoginController@index');
//Logout seasson...
Route::get('logout', 'LoginController@logout');

//MAIN
Route::get('main', 'MainController@index');
Route::get('main/usuarios', 'MainController@usuarios');
Route::get('main/zonageo', 'MainController@zonageo');
Route::get('main/ausentismo', 'MainController@ausentismo');
Route::get('main/horarios', 'MainController@horarios');
Route::get('main/marcado', 'MainController@marcado');
//Recuperación PW
Route::get('main/cambiapw', 'MainController@cambiapw');
//Cambiar la contraseña
Route::post('main/pwreset', 'MainController@pwreset');

//USUARIOS
Route::resource('main/usuarios/administrar', 'UsuariosController');
Route::get('main/usuarios/nuevo','UsuariosController@nuevo');
Route::get('main/usuarios/export','UsuariosController@exportaUsuario');
Route::post('main/usuarios/administrar/borra','UsuariosController@delete');

//CELULARES
Route::resource('main/usuarios/administrarcel', 'CelularController');
Route::post('main/usuarios/administrarcel/borra','CelularController@delete');
Route::get('main/usuarios/celular','CelularController@celular');
Route::get('main/usuarios/exportcel','CelularController@exportaCelular');

//ZONAS GEOGRÁFICAS
Route::resource('main/zonageo/administrar', 'ZonaGeoController');
Route::resource('main/zonageo/asigadministrar', 'AsigZonaGeoController');
Route::post('main/zonageo/administrar/borra','ZonaGeoController@delete');
Route::post('main/zonageo/asigadministrar/borra','AsigZonaGeoController@delete');
Route::get('main/zonageo/nuevo','ZonaGeoController@nuevo');
Route::get('main/zonageo/asignuevo','AsigZonaGeoController@nuevo');
Route::get('main/zonageo/export','ZonaGeoController@exportaZonaGeo');
Route::get('main/zonageo/asigexport','AsigZonaGeoController@exportaZonaGeo');

//AUSENTISMO
Route::resource('main/ausentismo/administrar', 'AusentismoController');
Route::resource('main/ausentismo/asigadministrar', 'AsigAusentismoController');
Route::post('main/ausentismo/administrar/borra','AusentismoController@delete');
Route::post('main/ausentismo/asigadministrar/borra','AsigAusentismoController@delete');
Route::get('main/ausentismo/nuevo','AusentismoController@nuevo');
Route::get('main/ausentismo/asignuevo','AsigAusentismoController@nuevo');
Route::get('main/ausentismo/export','AusentismoController@exportaAusentismo');
Route::get('main/ausentismo/asigexport','AsigAusentismoController@exportaAusentismo');

//HORARIOS
Route::resource('main/horarios/administrar', 'HorariosController');
Route::resource('main/horarios/asigadministrar', 'AsigHorariosController');
Route::post('main/horarios/administrar/borra','HorariosController@delete');
Route::post('main/horarios/asigadministrar/borra','AsigHorariosController@delete');
Route::get('main/horarios/nuevo','HorariosController@nuevo');
Route::get('main/horarios/asignuevo','AsigHorariosController@nuevo');
Route::get('main/horarios/export','HorariosController@exportaHorario');
Route::get('main/horarios/asigexport','AsigHorariosController@exportaHorario');

//MARCAS Y CONSULTAS DE MARCAS
Route::resource('main/marcado/administrar', 'MarcadoController');
Route::get('main/marcado/marcau','MarcadoController@marcau');
Route::post('main/marcado/administrar/borra','MarcadoController@delete');
Route::get('main/marcado/reporte','MarcadoController1@reporte');
Route::get('main/marcado/export','MarcadoController@exportaMarcas');

app/Http/Controllers/UsuariosController.php
<?php namespace Asistance\Http\Controllers;

use Asistance\Http\Requests;
use Asistance\Http\Controllers\Controller;

use Illuminate\Http\Request;
use Asistance\Http\Requests\UsuarioRequest;

//Enlace a la ruta del modelo:
use Asistance\ModelUsuario;
//Enlace a la ruta de los celulares
use Asistance\ModelCelular;

//Para llamar a atributos reservados especiales:
use Illuminate\Support\Facades\Session; 
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Hash;
use DB;
use Maatwebsite\Excel\Facades\Excel;

class UsuariosController extends Controller {

	/*Protegiendo las rutas asociadas a este controlador */
	public function __construct()
	{
		$this->middleware('auth');
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$usuarios = DB::table('Usuario')
			->where('Usuario.deleted_at','=',null)
			->join('Celular', 'Celular.id_celular', '=', 'Usuario.Telefono')
			->orderBy('RUT', 'DESC')
			->paginate(10);
		return view('sistema.usuarios.administra',compact('usuarios'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(UsuarioRequest $request)
	{
		//Primera lógica de guardado: Buscar si el alias de usuario existe o no en el softdelete
		$logica=false;
		$comparadors=ModelUsuario::onlyTrashed()->get(); //sólo valores softdeleteados.
		foreach($comparadors as $comparador)
		{
			if($comparador->RUT == $request->RUT) //comparación)
			{
				$logica= true;
				break;
			}
		}
		//Segunda lógica: buscar el RUT en los valores normales no softdeleteados
		unset($comparadors); //limpieza de variable
		$comparadors=ModelUsuario::All();
		$logica2=false;
		foreach($comparadors as $comparador)
		{
			if($comparador->RUT == $request->RUT) //comparación)
			{
				$logica2= true;
				break;
			}
		}
		//Se compara logica, si es true significa que el alias ya fue empleado. hay que comparar la negación
		if($logica)
		{
			//Simplemente, se vuelve a validar el uso de ese usuario cuando hay registro previo y si hay registro de borrado en deleted_at
			ModelUsuario::withTrashed()->find($request->RUT)->restore();
			Session::flash('message', 'No se genera nuevo usuario, pero se habilita usuario creado anteriormente.');
			return Redirect::to('main\usuarios\nuevo');
		}
		elseif(!$logica2)
		{
			ModelUsuario::create
			([
				'RUT' =>$request['RUT'],
				'Apellido_P' => $request['Apellido_P'],
				'Apellido_M' => $request['Apellido_M'],
				'Nombres' => $request['Nombres'],
				'Domicilio' =>$request['Domicilio'],
				'Telefono' => $request['Telefono'],
				'Fecha_nacimiento' =>$request['Fecha_nacimiento'],
				'Fecha_ingreso' => $request['Fecha_ingreso'],
				'Rol' => $request['Rol'],
				'password' => $request['password'],
				'email' =>$request['email'],
			]);
			Session::flash('message', 'Nuevo usuario agregado exitosamente');
			return Redirect::to('main/usuarios/nuevo');
		}
		else
		{
			Session::flash('message', 'No se genera nuevo usuario, ya existe uno con el mismo rut.');
			return Redirect::to('main/usuarios/nuevo');
		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id, Request $request)
	{
		try
		{
			$RUT=$request->get('RUT');
			$email=$request->get('email');
			$Apellido_P=$request->get('Apellido_P');
			$Apellido_M=$request->get('Apellido_M');
			$Nombres=$request->get('Nombres');
			$usuarios = ModelUsuario::orderBy('RUT', 'DESC')
				->RUT($RUT)
				->email($email)
				->Apellido_P($Apellido_P)
				->Apellido_M($Apellido_M)
				->Nombres($Nombres)
				->paginate(10);
			return view('sistema.usuarios.administra',compact('usuarios'));
		}
		catch(\Exception $e)
		{
			Session::flash('message', 'Imposible filtrar. Dato en uso actualmente.');
			return Redirect::to('main/usuarios/nuevo');
		}
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$usuario=ModelUsuario::find($id);
		$celulars=ModelCelular::All();
		return view('sistema.usuarios.edit',['usuario'=>$usuario], compact('celulars'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id, UsuarioRequest $request)
	{
		$usuario=ModelUsuario::find($id);
		$usuario->fill($request->all());
		$usuario->save();
		Session::flash('message', 'Edición realizada exitosamente');
		return Redirect::to('main\usuarios\administrar');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		try
		{
			//Notar que este método no eliminará nada sino que ocultará regstros.
			$usuario=ModelUsuario::find($id);
			$usuario->delete();
			Session::flash('message', 'Eliminación realizada exitosamente');
			return Redirect::to('main\usuarios\administrar');
		}
		catch(\Exception $e)
		{
			Session::flash('message', 'Imposible borrar. Usuario activo en uso actualmente.');
			return Redirect::to('main\ausentismo\administrar');
		}
	}
	
	public function nuevo()
    {
		$celulars=ModelCelular::All();
        return view('sistema.usuarios.nuevo', compact('celulars'));
	}

	public function delete(Request $request)
	{
		try
		{
			//Se recolecta en un arreglo, todas las ID a borrar
			$delets=$request->delete;
			//Evitar errores con un if... en caso que no existan checkboxs seleccionados es decir, no hay $delets
			if($delets)
			{	
				//Se recorre el arreglo $delets... para hacer el borrado
				foreach($delets as $delet)
				{
					$usuario=ModelUsuario::find($delet);
					$usuario->delete();
				}
				Session::flash('message', 'Eliminación masiva realizada exitosamente');
				return Redirect::to('main\usuarios\administrar');
			}
			else
			{
				Session::flash('message', 'No se han efectuado selecciones.');
				return Redirect::to('main\usuarios\administrar');
			}			
		}
		catch(\Exception $e)
		{
			Session::flash('message', 'Imposible borrar. Usuario activo en uso actualmente.');
			return Redirect::to('main\usuarios\administrar');
		}
	}

	public function exportaUsuario()
	{
		Excel::create('Usuarios(Listado)', function($excel){
			$excel->sheet('Usuarios', function($sheet){
				$data = ModelUsuario::where('deleted_at', '=', null)->join('Celular', 'Usuario.Telefono', '=', 'Celular.id_celular')
					->select('RUT', 'Apellido_P', 'Apellido_M', 'Nombres', 'Domicilio', 'Numero_celular', 'email', 'Rol')
					->selectRaw("DATE_FORMAT(Fecha_nacimiento,'%d-%m-%Y')")->selectRaw("DATE_FORMAT(Fecha_ingreso,'%d-%m-%Y')")
					->get(); 
				$sheet->fromArray($data);
				$sheet->cell('B1', function($cell) { $cell->setValue('Apellido Paterno'); });
				$sheet->cell('C1', function($cell) { $cell->setValue('Apellido Materno'); });
				$sheet->cell('F1', function($cell) { $cell->setValue('Número Celular'); });
				$sheet->cell('I1', function($cell) { $cell->setValue('Fecha Nacimiento'); });
				$sheet->cell('J1', function($cell) { $cell->setValue('Fecha Ingreso'); });
			});
		})->download('xls');
		return back();
	}	
}

resources/views/sistema/usuarios/administra.blade.php
@extends('layouts.principal')

@section('bienvenida')
    <h1>Usuarios</h1>
    <p>Bienvenidos a Asistance. Administración de usuarios</p>
    <p>Buscar</p>
    @include('alertas.alerta')
    @include('alertas.validaformulario')

        {!! Form::open(['route' => 'main.usuarios.administrar.show', 'method' => 'GET'])!!}
        <div class="fields">
            <div class="field quarter">
            {!! Form::label('RUT', 'Buscar por rut de usuario: ') !!}
            {!! Form::text('RUT', null, ['class' => 'form-control', 'onkeypress' => 'return soloNumeroNatural(event)', 'maxlength' => '10', 'value' => old('RUT'), 'placeholder' => 'Ejemplo: 123452157']) !!}
            </div>
            <div class="field quarter">
            {!! Form::label('email', 'Buscar por correo de usuario: ') !!}
            {!! Form::text('email', null, ['class' => 'form-control', 'maxlength' => '40', 'value' => old('email'), 'placeholder' => 'Ejemplo: hola@hola.cl']) !!}
            </div>
            <div class="field quarter">
            {!! Form::label('Apellido_P', 'Ingrese apellido paterno: ') !!}
            {!! Form::text('Apellido_P', null, ['class' => 'form-control', 'maxlength' => '15', 'value' => old('Apellido_P'), 'placeholder' => 'Ejemplo: González']) !!}
            </div>
            <div class="field quarter">
            {!! Form::label('Apellido_M', 'Ingrese apellido materno: ') !!}
            {!! Form::text('Apellido_M', null, ['class' => 'form-control', 'maxlength' => '15', 'value' => old('Apellido_M'), 'placeholder' =>'Ejemplo: Pérez']) !!}
            </div>
            <div class="field half">
            {!! Form::label('Nombres', 'Ingrese sus nombres: ') !!}
            {!! Form::text('Nombres', null, ['class' => 'form-control', 'maxlength' => '25', 'value' => old('Nombres'), 'placeholder' => 'Ejemplo: Juan Carlos']) !!}
            </div>
        </div>
        <p></p>    
        {!! Form::submit('Mostrar resultados',['class' => 'button small']) !!}
        {!! Form::close()!!}
        <h4></h4>
        <a href="{{ url('main/usuarios/export')}}" class="button submit">Exporta todos los usuarios *xls</a>
        <p></p>
        <h2>Tabla de usuarios</h2>
        {!! Form::open(['url' => 'main/usuarios/administrar/borra', 'method' => 'POST']) !!}
        <table class="table" align="center" size="small">
                <thead> 
                    <th>Operación</th>
                    <th align="center">Check</th>
                    <th>RUT</th>
                    <th>Nombre</th>
                    <th>Rol</th>
                    <th>Celular</th>
                </thead>
            @foreach($usuarios as $usuario) 
            <!-- Condición para que la tabla de ediciones no muestre al usuario activo de la sesión -->
            @if($usuario->RUT != Auth::user()->RUT )
                <tbody>
                    <td>{!! link_to_route('main.usuarios.administrar.edit', $title = 'Modificar', $parameters = $usuario->RUT , $attributes = ['class'=>'btn btn-primary']) !!}</td>
                    <td align="center"><input id="{{$usuario->RUT}}" value="{{$usuario->RUT}}" name="delete[]" type="checkbox" class="checkthis"/><label for="{{$usuario->RUT}}"></label></td>
                    <td>{{$usuario->RUT}}</td>
                    <td>{{$usuario->Apellido_P}} {{$usuario->Apellido_M}} {{$usuario->Nombres}}</td>
                    <td>{{$usuario->Rol}}</td>
                    <td>{{$usuario->Numero_celular}}</td>
                </tbody>
            @endif
            @endforeach
        </table>	
        {!! $usuarios->render()!!}
        <br/><br/>
        {!! Form::submit('Eliminar check',['class' => 'button small']) !!}
        {!! Form::close()!!}
@stop            

@section('submenu')
@include('menus.usuarios')
@stop           

@section('subseccion11')
@include('menus.menus_ayuda')
@stop  

resources/views/sistema/usuarios/administracel.blade.php
@extends('layouts.principal')

@section('bienvenida')
    <h1>Usuarios</h1>
    <p>Bienvenidos a Asistance</p>
    <p>Administración de usuarios (celular). Especificar operación</p>
    
    @include('alertas.alerta')
    @include('alertas.validaformulario')
    <!-- Buscar -->
    {!! Form::open(['route' => 'main.usuarios.administrarcel.show', 'method' => 'GET'])!!}
        <div class="fields">
            <div class="field quarter">
            {!! Form::label('Numero_celular', 'Buscar por celular: ') !!}
            {!! Form::text('Numero_celular', null, ['class' => 'form-control', 'onkeypress' => 'return soloNumeroNatural(event)', 'maxlength' => '11', 'value' => old('Numero_celular'), 'placeholder' =>'Ejemplo: 99872345']) !!}
            </div>
        </div>
    <p></p>    
    {!! Form::submit('Mostrar resultados',['class' => 'button small']) !!}
    {!! Form::close()!!}
    <h4></h4>
    <!-- Exportar Excel -->
    <a href="{{ url('main/usuarios/exportcel')}}" class="button submit">Exporta todos los celulares *xls</a>
    <p></p>
    <!-- Tabla -->
    <h2>Tabla de celulares</h2>
        {!! Form::open(['url' => 'main/usuarios/administrarcel/borra', 'method' => 'post']) !!}
        <table class="table" align="center" size="small">
                <thead>
                    <th>Operación</th>
                    <th align="center">Check</th>
                    <th>Número celular</th>
                    <th>Compañía</th>
                    <th>IMEI</th>
                </thead>
            @foreach($celulars as $celular) 
                <tbody>
                    <td>{!! link_to_route('main.usuarios.administrarcel.edit', $title = 'Modificar', $parameters = $celular->id_celular , $attributes = ['class'=>'btn btn-primary']) !!}</td>
                    <td align="center"><input id="{{$celular->id_celular}}" value="{{$celular->id_celular}}" name="delete[]" type="checkbox" class="checkthis"/><label for="{{$celular->id_celular}}"></label></td>
                    <td>{{$celular->Numero_celular}}</td>
                    <td>{{$celular->Compania}}</td>
                    <td>{{$celular->IMEI}}</td>
                </tbody>
            @endforeach
        </table>
        {!! $celulars->render()!!}
        <p></p>
        <!-- Eliminación masiva -->
        {!! Form::submit('Eliminar check',['class' => 'button small']) !!}
        {!! Form::close()!!}
@stop            

@section('submenu')
@include('menus.usuarios')
@stop           

@section('subseccion11')
@include('menus.menus_ayuda')
@stop  

resources/views/sistema/usuarios/celular.blade.php
@extends('layouts.principal')

@section('bienvenida')
    <h1>Usuarios</h1>
    <p>Bienvenidos a Asistance</p>
	<p>Nuevo celular a agregar. Favor complete formulario</p>
	
	@include('alertas.alerta')
	@include('alertas.validaformulario')
	<section>
		<!--Formulario para crear un nuevo celular y ser almacenado a la BBDD -->
		{!! Form::open(['route' => 'main.usuarios.administrarcel.store', 'method' => 'POST']) !!}
			<div class="fields">
				<div class="field half">
					{!! Form::label('Numero_celular', 'Ingrese número celular: ') !!}
					{!! Form::text('Numero_celular', null, ['class' => 'form-control', 'onkeypress' => 'return soloNumeroNatural(event)', 'minlength' => '7', 'maxlength' => '11', 'placeholder' =>'Ejemplo: 99872345']) !!}
                </div>
                <div class="field half">
                    {!! Form::label('Compania', 'Ingrese compañía (opcional): ') !!}
                    {!! Form::text('Compania', null, ['class' => 'form-control', 'maxlength' => '18', 'placeholder' =>'Ejemplo: Entel']) !!}
                    </div>
				<div class="field half">
                    {!! Form::label('IMEI', 'Ingrese IMEI del equipo (opcional): ') !!}
                    {!! Form::text('IMEI', null, ['class' => 'form-control', 'maxlength' => '18','placeholder' =>'Ejemplo: 1111-1111-1111']) !!}
				</div>
			</div>
			<ul class="actions">
				<li>
				{!! Form::submit('Generar nuevo ceular',['class' => 'btn btn-primary']) !!}
				</li>
			</ul>
		{!! Form::close() !!}
	</section>	
@stop            

@section('submenu')
@include('menus.usuarios')
@stop           

@section('subseccion11')
@include('menus.menus_ayuda')
@stop  

resources/views/sistema/usuarios/edit.blade.php
@extends('layouts.principal')

@section('bienvenida')
    <h1>Usuarios</h1>
    <p>Bienvenidos a Asistance</p>
    <p>Administración de usuarios. Efectúe su edición</p>
	@include('alertas.alerta')
	@include('alertas.validaformulario')
    {!! Form::model($usuario, ['route' => ['main.usuarios.administrar.update', $usuario->RUT], 'method' => 'PUT']) !!}
        <div class="fields">
            <div class="field">
                {!! Form::label('RUT', 'RUT de usuario a actualizar: ') !!}
                {!! Form::text('RUT', null, ['readonly'=>'readonly', 'class' => 'form-control']) !!}			
            </div>
            <div class="field half">
                {!! Form::label('Apellido_P', 'Ingrese apellido paterno: ') !!}
                {!! Form::text('Apellido_P', null, ['class' => 'form-control', 'maxlength' => '15', 'placeholder' => 'Ejemplo: González']) !!}
            </div>
            <div class="field half">
                {!! Form::label('Apellido_M', 'Ingrese apellido materno: ') !!}
                {!! Form::text('Apellido_M', null, ['class' => 'form-control', 'maxlength' => '15', 'placeholder' =>'Ejemplo: Pérez']) !!}
            </div>
            <div class="field">
                {!! Form::label('Nombres', 'Ingrese sus nombres: ') !!}
                {!! Form::text('Nombres', null, ['class' => 'form-control', 'maxlength' => '25', 'placeholder' => 'Ejemplo: Juan Carlos']) !!}
            </div>
            <div class="field">
                {!! Form::label('Domicilio', 'Ingrese domicilio: ') !!}
                {!! Form::text('Domicilio', null, ['class' => 'form-control', 'maxlength' => '50', 'placeholder' => 'Ejemplo: Los Tucanes 4567']) !!}
            </div>
            <div class="field half">
            {!! Form::label('Telefono', 'Seleccionar celular asignado: ') !!}
                <select name="Telefono" id="Telefono" class="form-control" required="required">
                    @foreach($celulars as $celular)
                        <option value="{{ $celular->id_celular}}" id="{{ $celular->id_celular}}" name="{{ $celular->id_celular}}">{{ $celular->Numero_celular }}</option>
                    @endforeach
                </select>
            </div>
            <div class="field half">
                {!! Form::label('Fecha_nacimiento', 'Seleccionar fecha nacimiento: ') !!}
                {!! Form::date('Fecha_nacimiento', \Carbon\Carbon::now(), ['id' => 'datepicker','class' => 'form-control', 'placeholder' =>'Ejemplo: 30-03-2000', 'step'=>'1']) !!}
            </div>
            <div class="field half">
                {!! Form::label('Fecha_ingreso', 'Seleccionar fecha ingreso a la compañia: ') !!}
                {!! Form::date('Fecha_ingreso', \Carbon\Carbon::now(), ['id' => 'datepicker','class' => 'form-control', 'placeholder' =>'Ejemplo: 30-03-2000', 'step'=>'1']) !!}
            </div>
            <div class="field quarter">
                {!! Form::label('Rol', 'Seleccionar rol de usuario: ') !!}
                {!!	Form::select('Rol', ['Trabajador'=>'Trabajador','Administrativo'=> 'Administrativo'], 'Trabajador') !!}
            </div>
            <div class="field">
                {!! Form::label('password', 'Ingrese contraseña inicial a asignar: ') !!}
                {!! Form::text('password', 1111, ['class' => 'form-control', 'maxlength' => '30', 'minlength' => '4']) !!}
            </div>
            <div class="field">
                {!! Form::label('email', 'Correo electrónico: ') !!}
                {!! Form::email('email', null, ['class' => 'form-control', 'maxlength' => '40', 'placeholder' => 'Ejemplo: hola@hola.cl']) !!}
            </div>
        </div>
    <ul class="actions">
    <li>
    {!! Form::submit('Actualizar',['class' => 'btn btn-primary']) !!}
    </li>
    </ul>
    {!! Form::close() !!}

    {!! Form::open(['route' => ['main.usuarios.administrar.destroy', $usuario->RUT], 'method' => 'DELETE']) !!}
        <ul class="actions">
    <li>{!! Form::submit('Eliminar',['class' => 'btn btn-danger']) !!}</li>
        </ul>
    {!! Form::close() !!}
@stop            

@section('submenu')
@include('menus.usuarios')
@stop           

@section('subseccion11')
@include('menus.menus_ayuda')
@stop   

resources/views/sistema/usuarios/editcel.blade.php
@extends('layouts.principal')

@section('bienvenida')
    <h1>Usuarios</h1>
    <p>Bienvenidos a Asistance</p>
    <p>Administración de usuarios (celular). Efectúe su edición</p>
    @include('alertas.alerta')
	@include('alertas.validaformulario')
    {!! Form::model($celular, ['route' => ['main.usuarios.administrarcel.update', $celular->id_celular], 'method' => 'PUT']) !!}
    <div class="fields">
        <div class="field half">
            {!! Form::label('Numero_celular', 'Ingrese número celular: ') !!}
            {!! Form::text('Numero_celular', null, ['class' => 'form-control', 'onkeypress' => 'return soloNumeroNatural(event)', 'minlength' => '7', 'maxlength' => '11', 'placeholder' =>'Ejemplo: 99872345']) !!}
        </div>
        <div class="field half">
            {!! Form::label('Compania', 'Ingrese compañía (opcional): ') !!}
            {!! Form::text('Compania', null, ['class' => 'form-control', 'maxlength' => '18', 'placeholder' =>'Ejemplo: Entel']) !!}
            </div>
        <div class="field half">
            {!! Form::label('IMEI', 'Ingrese IMEI del equipo (opcional): ') !!}
            {!! Form::text('IMEI', null, ['class' => 'form-control', 'maxlength' => '18','placeholder' =>'Ejemplo: 1111-1111-1111']) !!}
        </div>
    </div>     
    <ul class="actions">
    <li>
    {!! Form::submit('Actualizar',['class' => 'btn btn-primary']) !!}
    </li>
    </ul>
    {!! Form::close() !!}

    {!! Form::open(['route' => ['main.usuarios.administrarcel.destroy', $celular->id_celular], 'method' => 'DELETE']) !!}
        <ul class="actions">
    <li>{!! Form::submit('Eliminar',['class' => 'btn btn-danger']) !!}</li>
        </ul>
    {!! Form::close() !!}
@stop            

@section('submenu')
@include('menus.usuarios')
@stop           

@section('subseccion11')
@include('menus.menus_ayuda')
@stop   