app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
//LOGIN
Route::resource('login', 'LoginController');
Route::get('/', 'LoginController@index');
//Logout seasson...
Route::get('logout', 'LoginController@logout');

//MAIN
Route::get('main', 'MainController@index');
Route::get('main/usuarios', 'MainController@usuarios');
Route::get('main/zonageo', 'MainController@zonageo');
Route::get('main/ausentismo', 'MainController@ausentismo');
Route::get('main/horarios', 'MainController@horarios');
Route::get('main/marcado', 'MainController@marcado');
//Recuperación PW
Route::get('main/cambiapw', 'MainController@cambiapw');
//Cambiar la contraseña
Route::post('main/pwreset', 'MainController@pwreset');

//USUARIOS
Route::resource('main/usuarios/administrar', 'UsuariosController');
Route::get('main/usuarios/nuevo','UsuariosController@nuevo');
Route::get('main/usuarios/export','UsuariosController@exportaUsuario');
Route::post('main/usuarios/administrar/borra','UsuariosController@delete');

//CELULARES
Route::resource('main/usuarios/administrarcel', 'CelularController');
Route::post('main/usuarios/administrarcel/borra','CelularController@delete');
Route::get('main/usuarios/celular','CelularController@celular');
Route::get('main/usuarios/exportcel','CelularController@exportaCelular');

//ZONAS GEOGRÁFICAS
Route::resource('main/zonageo/administrar', 'ZonaGeoController');
Route::resource('main/zonageo/asigadministrar', 'AsigZonaGeoController');
Route::post('main/zonageo/administrar/borra','ZonaGeoController@delete');
Route::post('main/zonageo/asigadministrar/borra','AsigZonaGeoController@delete');
Route::get('main/zonageo/nuevo','ZonaGeoController@nuevo');
Route::get('main/zonageo/asignuevo','AsigZonaGeoController@nuevo');
Route::get('main/zonageo/export','ZonaGeoController@exportaZonaGeo');
Route::get('main/zonageo/asigexport','AsigZonaGeoController@exportaZonaGeo');

//AUSENTISMO
Route::resource('main/ausentismo/administrar', 'AusentismoController');
Route::resource('main/ausentismo/asigadministrar', 'AsigAusentismoController');
Route::post('main/ausentismo/administrar/borra','AusentismoController@delete');
Route::post('main/ausentismo/asigadministrar/borra','AsigAusentismoController@delete');
Route::get('main/ausentismo/nuevo','AusentismoController@nuevo');
Route::get('main/ausentismo/asignuevo','AsigAusentismoController@nuevo');
Route::get('main/ausentismo/export','AusentismoController@exportaAusentismo');
Route::get('main/ausentismo/asigexport','AsigAusentismoController@exportaAusentismo');

//HORARIOS
Route::resource('main/horarios/administrar', 'HorariosController');
Route::resource('main/horarios/asigadministrar', 'AsigHorariosController');
Route::post('main/horarios/administrar/borra','HorariosController@delete');
Route::post('main/horarios/asigadministrar/borra','AsigHorariosController@delete');
Route::get('main/horarios/nuevo','HorariosController@nuevo');
Route::get('main/horarios/asignuevo','AsigHorariosController@nuevo');
Route::get('main/horarios/export','HorariosController@exportaHorario');
Route::get('main/horarios/asigexport','AsigHorariosController@exportaHorario');

//MARCAS Y CONSULTAS DE MARCAS
Route::resource('main/marcado/administrar', 'MarcadoController');
Route::get('main/marcado/marcau','MarcadoController@marcau');
Route::post('main/marcado/administrar/borra','MarcadoController@delete');
Route::get('main/marcado/reporte','MarcadoController1@reporte');
Route::get('main/marcado/export','MarcadoController@exportaMarcas');

app/Http/Controllers/ZonaGeoController.php
<?php namespace Asistance\Http\Controllers;

use Asistance\Http\Requests;
use Asistance\Http\Controllers\Controller;

use Illuminate\Http\Request;
use Asistance\Http\Requests\GeolocalizacionRequest;
//Enlace a la ruta del modelo:
use Asistance\ModelGeolocalizacion;
//Para llamar a atributos reservados especiales:
use Illuminate\Support\Facades\Session; 
use Illuminate\Support\Facades\Redirect;
use DB;
use Maatwebsite\Excel\Facades\Excel;

class ZonaGeoController extends Controller {

	/*Protegiendo las rutas asociadas a este controlador */
	public function __construct()
	{
		$this->middleware('auth');
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$zonageos= ModelGeolocalizacion::orderBy('Alias_loc_geo', 'DESC')
			->paginate(15);
		return view('sistema.zonageo.administra',compact('zonageos'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(GeolocalizacionRequest $request)
	{
		//Primera lógica de guardado: Buscar si el alias de zonageográfica existe o no en el softdelete
		$logica=false;
		$comparadors=ModelGeolocalizacion::onlyTrashed()->get(); //sólo valores softdeleteados.
		foreach($comparadors as $comparador)
		{
			if($comparador->Alias_loc_geo == $request->Alias_loc_geo) //comparación)
			{
				$logica= true;
				break;
			}
		}
		//Segunda lógica: buscar el alias de loc geo en los valores normales no softdeleteados
		unset($comparadors); //limpieza de variable
		$comparadors=ModelGeolocalizacion::All();
		$logica2=false;
		foreach($comparadors as $comparador)
		{
			if($comparador->Alias_loc_geo == $request->Alias_loc_geo) //comparación)
			{
				$logica2= true;
				break;
			}
		}
		//Se compara logica, si es true significa que el alias ya fue empleado. hay que comparar la negación
		if($logica)
		{
			//Simplemente, se vuelve a validar el uso de ese usuario cuando hay registro previo y si hay registro de borrado en deleted_at
			ModelGeolocalizacion::withTrashed()-> where('Alias_loc_geo', '=', $request->Alias_loc_geo ) ->restore();
			Session::flash('message', 'No se genera nueva zona geográfica, pero se habilita zona creada anteriormente.');
			return Redirect::to('main\zonageo\nuevo');
		}
		//Se compara logica, si es false significa que el alias ya fue empleado.
		elseif(!$logica2)
		{
			//Verificación de coherencia de los puntos seleccionados en el mapa:
			//La lógica del eje X es longitud. Lógica eje Y es latitud.
			/*
									(dot)X2Y2

					(dot)X1Y1
			*/
		if ($request->coorX1 > $request->coorX2)
		//Si los puntos no corresponden se hará un intercambio de variables.
		//Recordar la condición normal correcta: $request->coorX1 < $request->coorX2) || ($request->coorY2 > $request->coorY1
		{
			//Intercambio eje X
			$cambio=$request->coorX1;
			$request->coorX1=$request->coorX2;
			$request->coorX2=$cambio;
		}
		if($request->coorY2 < $request->coorY1)
		{
			//Intercambio eje Y
			$cambio=$request->coorY1;
			$request->coorY1=$request->coorY2;
			$request->coorY2=$cambio;
		}
				ModelGeolocalizacion::create
				([
					'Alias_loc_geo' =>$request['Alias_loc_geo'],
					'coorX1' => $request['coorX1'],
					'coorY1' => $request['coorY1'],
					'coorX2' => $request['coorX2'],
					'coorY2' => $request['coorY2'],
				]);
					Session::flash('message', 'Nueva zona geográfica generada exitosamente');
					return Redirect::to('main/zonageo/nuevo');
		}
		else
		{
			Session::flash('message', 'Nueva zona geográfica no generada. Ya existe una zona con el mismo nombre.');
			return Redirect::to('main/zonageo/nuevo');
		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id, Request $request)
	{
		try
		{
			$Alias_loc_geo=$request->get('Alias_loc_geo');
			//Asignación a variable consulta de todos los elementos de la tabla de la relación "ZonaGeo"
			$zonageos= ModelGeolocalizacion::orderBy('Alias_loc_geo', 'DESC')
				->Alias_loc_geo($Alias_loc_geo)
				->paginate(15);

			//Retorno de la vista asociasa a edición
			return view('sistema.zonageo.administra',compact('zonageos'));
		}
		catch(\Exception $e)
		{
			Session::flash('message', 'Imposible filtrar. Dato en uso actualmente.');
			return Redirect::to('main\zonageo\administrar');
		}
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$zonageo=ModelGeolocalizacion::find($id);
		return view('sistema.zonageo.edit',['zonageo'=>$zonageo]);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id, GeolocalizacionRequest $request)
	{
		$zonageo=ModelGeolocalizacion::find($id);
		//Si los puntos no corresponden se hará un intercambio de variables.
		//Recordar la condición normal correcta: $request->coorX1 < $request->coorX2) || ($request->coorY2 > $request->coorY1
		if ($request->coorX1 > $request->coorX2 && $request->coorY2 < $request->coorY1)
		{
			$zonageo->fill([
				'coorX1' => $request['coorX2'],
				'coorY1' => $request['coorY2'],
				'coorX2' => $request['coorX1'],
				'coorY2' => $request['coorY1'],
			]);
			$zonageo->save();
		}
		elseif ($request->coorX1 > $request->coorX2)
		{
			$zonageo->fill([
				'coorX1' => $request['coorX2'],
				'coorY1' => $request['coorY1'],
				'coorX2' => $request['coorX1'],
				'coorY2' => $request['coorY2'],
			]);
			$zonageo->save();
		}
		elseif($request->coorY2 < $request->coorY1)
		{
			$zonageo->fill([
				'coorX1' => $request['coorX1'],
				'coorY1' => $request['coorY2'],
				'coorX2' => $request['coorX2'],
				'coorY2' => $request['coorY1'],
			]);
			$zonageo->save();
		}
		else
		{
			$zonageo->fill([
				'coorX1' => $request['coorX1'],
				'coorY1' => $request['coorY1'],
				'coorX2' => $request['coorX2'],
				'coorY2' => $request['coorY2'],
			]);
			$zonageo->save();
		}		
			Session::flash('message', 'Edición realizada exitosamente');
			return Redirect::to('main\zonageo\administrar');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		try
		{
			//Antes de eliminar una zona geográfica, hay que asegurarse que el número no esté asignado a un trabajador
			$asignacion = DB::table('Asignacion_loc_geo')->get();
			$logica = true;
			foreach($asignacion as $asigna)
			{
				if($asigna->id_loc_geo == $id)
				{
					$logica = false;
					break;
				}
			}
			//$logica será verdadero en el caso que la zona no esté previamente asignado.
			if($logica)
			{
				$zonageo=ModelGeolocalizacion::find($id);
				$zonageo->delete();
				Session::flash('message', 'Eliminación realizada exitosamente');
				return Redirect::to('main\zonageo\administrar');
			}
			else
			{
				Session::flash('message', 'Zona geográfica asignada a uno o varios usuarios. Desasignar antes de borrar.');
				return Redirect::to('main\zonageo\administrar');
			}			
		}
		catch(\Exception $e)
		{
			Session::flash('message', 'Imposible borrar. Dato en uso actualmente.');
			return Redirect::to('main\zonageo\administrar');
		}
	}

	public function nuevo()
    {
        return view('sistema.zonageo.nuevo');
	}

	public function delete(Request $request)
	{
		try
		{
			//Se recolecta en un arreglo, todas las ID a borrar
			$delets=$request->delete;
			//Evitar errores con un if... en caso que no existan checkboxs seleccionados es decir, no hay $delets
			if($delets)
			{
				//Un primer foreach doble, para revisar que los delets elegidos no estén en uso.
				$asignacion = DB::table('Asignacion_loc_geo')->get();
				$logica = true;	
				foreach($delets as $delet)
				{
					foreach($asignacion as $asigna)
					{
						if($asigna->id_loc_geo == $delet)
						{
							$logica = false;
							break;
						}
					}
				}
				if($logica)
				{
					//Se recorre el arreglo $delets... para hacer el borrado
					foreach($delets as $delet)
					{
						$zonageo=ModelGeolocalizacion::find($delet);
						$zonageo->delete();
					}
					Session::flash('message', 'Eliminación masiva realizada exitosamente');
					return Redirect::to('main\zonageo\administrar');
				}
				else
				{
					Session::flash('message', 'Una o varias de las zonas geográficas seleccionados están asignados a uno o varios usuarios. Desasignar antes del borrado.');
					return Redirect::to('main\zonageo\administrar');
				}				
			}
			else
			{
				Session::flash('message', 'No se han efectuado selecciones.');
				return Redirect::to('main\zonageo\administrar');
			}			
		}
		catch(\Exception $e)
		{
			Session::flash('message', 'Imposible borrar. Dato en uso actualmente.');
			return Redirect::to('main\zonageo\administrar');
		}
	}

	public function exportaZonaGeo()
	{
		Excel::create('Zona_Geografica(Listado)', function($excel){
			$excel->sheet('Zonageo', function($sheet){
				$data = ModelGeolocalizacion::where('deleted_at', '=', null)
					->select('Alias_loc_geo', 'coorX1', 'coorY1', 'coorX2', 'coorY2')
					->get(); 
				$sheet->fromArray($data);
			});
		})->download('xls');
		return back();
	}
	
}

resources/views/sistema/zonageo/administra.blade.php
@extends('layouts.principal')

@section('bienvenida')
    <h1>Zonas Geográficas</h1>
    <p>Bienvenidos a Asistance</p>
    <p>Administración de zonas geográficas. Especificar operación</p>
    
	@include('alertas.alerta')
    @include('alertas.validaformulario')

    <!-- Buscar -->
    {!! Form::open(['route' => 'main.zonageo.administrar.show', 'method' => 'GET'])!!}
    <div class="fields">
        <div class="field half">
        {!! Form::label('Alias_loc_geo', 'Buscar por alias de Zona Geográfica: ') !!}
        {!! Form::text('Alias_loc_geo', null, ['class' => 'form-control', 'maxlength' => '16', 'value' => old('Alias_loc_geo'), 'placeholder' =>'Ejemplo: ZONAGEO-0001']) !!}
        </div>
    </div>      
    <p></p>
    {!! Form::submit('Mostrar resultados',['class' => 'button small']) !!}
    {!! Form::close()!!}
    <h4></h4>
    <!-- Exportar Excel -->
    <a href="{{ url('main/zonageo/export')}}" class="button submit">Exporta todas las zonas geográficas *xls</a>
    <p></p>
    <!-- Tabla -->
    <h2>Tabla de Zonas Geográficas</h2>
        {!! Form::open(['url' => 'main/zonageo/administrar/borra', 'method' => 'post']) !!}
        <table class="table" align="center" size="small">
                <thead>
                    <th>Operación</th>
                    <th>Check</th>
                    <th>Alias Zona geográfica</th>
                    <th>X1</th>
                    <th>Y1</th>
                    <th>X2</th>
                    <th>Y2</th>
                </thead>
            @foreach($zonageos as $zonageo) 
                <tbody>
                    <td>{!! link_to_route('main.zonageo.administrar.edit', $title = 'Modificar', $parameters = $zonageo->id_loc_geo , $attributes = ['class'=>'btn btn-primary']) !!}</td>
                    <td align="center"><input id="{{$zonageo->id_loc_geo}}" value="{{$zonageo->id_loc_geo}}" name="delete[]" type="checkbox" class="checkthis"/><label for="{{$zonageo->id_loc_geo}}"></label></td>
                    <td>{{$zonageo->Alias_loc_geo}}</td>
                    <td>{{$zonageo->coorX1}}</td>
                    <td>{{$zonageo->coorY1}}</td>
                    <td>{{$zonageo->coorX2}}</td>
                    <td>{{$zonageo->coorY2}}</td>
                </tbody>
            @endforeach
        </table>	
        {!! $zonageos->render()!!}
        <p></p>
        <!-- Eliminación masiva -->
        {!! Form::submit('Eliminar check',['class' => 'button small']) !!}
        {!! Form::close() !!}  
@stop            

@section('submenu')
@include('menus.zonageo')
@stop         

@section('subseccion11')
@include('menus.menus_ayuda')
@stop 

resources/views/sistema/zonageo/asigedit.blade.php
@extends('layouts.principal')

@section('bienvenida')
    <h1>Zonas Geográficas</h1>
    <p>Bienvenidos a Asistance</p>
    <p>Administración de asignación de zonas geográficas. Efectúe su edición</p>
    @include('alertas.alerta')
	@include('alertas.validaformulario')
    {!! Form::model($asigzonageo, ['route' => ['main.zonageo.asigadministrar.update', $asigzonageo->contador], 'method' => 'PUT']) !!}
    <div class="fields">
        <div class="field">
            {!! Form::label('RUT', 'RUT del trabajador: ') !!}
            {!! Form::text('RUT', null, ['class' => 'form-control', 'readonly'=>'readonly']) !!}
        </div>
        <div class="field half">
            {!! Form::label('ZonaGeo', 'Seleccione alias zona geográfica: ') !!}
            <select name="id_loc_geo" id="id_loc_geo" class="form-control" required="required">
                @foreach($zonageos as $zonageo)
                    <option value="{{ $zonageo->id_loc_geo}}" id="{{ $zonageo->id_loc_geo}}" name="{{ $zonageo->id_loc_geo}}">{{ $zonageo->Alias_loc_geo }}</option>
                @endforeach
            </select>
        </div>
        <div class="field half">
            {!! Form::label('TipoMarca', 'Seleccione el tipo de marca: ') !!}
            <select name="id_marcado" id="id_marcado" class="form-control" required="required">
                @foreach($tipomarcas as $tipomarca)
                    <option value="{{ $tipomarca->id_marcado}}" id="{{ $tipomarca->id_marcado}}" name="{{ $tipomarca->id_marcado}}">{{ $tipomarca->Tipo_marca }}</option>
                @endforeach
            </select>
        </div>
        <div class="field half">
            {!! Form::label('Fecha_inicio', 'Especifique fecha inicio de la asignación de zona: ') !!}
            {!! Form::date('Fecha_inicio', \Carbon\Carbon::now(), ['id' => 'datepicker','class' => 'form-control', 'placeholder' =>'Ejemplo: 30-03-2000', 'step'=>'1']) !!}
            </div>
        <div class="field half">
            {!! Form::label('Fecha_fin', 'Especifique fecha final de la asignación de zona: ') !!}
            {!! Form::date('Fecha_fin', \Carbon\Carbon::now(), ['id' => 'datepicker','class' => 'form-control', 'placeholder' =>'Ejemplo: 30-03-2000', 'step'=>'1']) !!}
        </div>
    </div>
    <ul class="actions">
    <li>
    {!! Form::submit('Actualizar',['class' => 'btn btn-primary']) !!}
    </li>
    </ul>
    {!! Form::close() !!}

    {!! Form::open(['route' => ['main.zonageo.asigadministrar.destroy', $asigzonageo->contador], 'method' => 'DELETE']) !!}
        <ul class="actions">
    <li>{!! Form::submit('Eliminar',['class' => 'btn btn-danger']) !!}</li>
        </ul>
    {!! Form::close() !!}
@stop            

@section('submenu')
@include('menus.zonageo')
@stop           
         

@section('subseccion11')
@include('menus.menus_ayuda')
@stop    

resources/views/sistema/zonageo/asignar.blade.php
@extends('layouts.principal')

@section('bienvenida')
    <h1>Zonas Geográficas</h1>
    <p>Bienvenidos a Asistance</p>
    <p>Administración de asignación de zonas geográficas a trabajadores</p>
    
	@include('alertas.alerta')
	@include('alertas.validaformulario')
        <!-- Buscar -->
        <h4>Filtros de visualización (rangos asociados a la fecha inicial de la asociación)</h4>
        {!! Form::open(['route' => 'main.zonageo.asigadministrar.show', 'method' => 'GET'])!!}
        <div class="fields">
            <div class="field half">
                {!! Form::label('RUT', 'Buscar por RUT del usuario: ') !!}<br/>
                <select name="RUT" id="RUT" class="form-control" required="required">
                @foreach($usuarios as $usuario)
                    <option value="{{ $usuario->RUT}}" id="{{ $usuario->RUT}}" name="{{ $usuario->RUT}}">{{ $usuario->RUT}}: {{ $usuario->Apellido_P}} {{ $usuario->Apellido_M}} {{ $usuario->Nombres }}</option>
                @endforeach
                </select>
            </div>
            <div class="field quarter">    
                {!! Form::label('fechaInicio', 'Buscar por fecha:  Inical') !!}         	
                {!! Form::date('fechaInicio', \Carbon\Carbon::now(), ['id' => 'datepicker','class' => 'form-control', 'placeholder' =>'Ejemplo: 30-03-2000', 'step'=>'1']) !!}
            </div>
            <div class="field quarter">    
                {!! Form::label('fechaFinal', 'Buscar por fecha: Final ') !!}         	
                {!! Form::date('fechaFinal', \Carbon\Carbon::now(), ['id' => 'datepicker','class' => 'form-control', 'placeholder' =>'Ejemplo: 30-03-2000', 'step'=>'1']) !!}
            </div>
        </div>
        <p></p>
        {!! Form::submit('Mostrar resultados',['class' => 'button small']) !!}
        {!! Form::close()!!}
        <h4></h4>
        <!-- Exportar Excel -->
        <h4>Filtros de exportación tabla (rangos asociados a la fecha inicial de la asociación)</h4>
        {!! Form::open(['url' => 'main/zonageo/asigexport', 'method' => 'GET']) !!}
        <div class="fields">
            <div class="field quarter">    
                {!! Form::label('fechaInicio', 'Fecha inicio: ') !!}         	
                {!! Form::date('fechaInicio', \Carbon\Carbon::now(), ['id' => 'datepicker','class' => 'form-control', 'placeholder' =>'Ejemplo: 30-03-2000', 'step'=>'1']) !!}
            </div>
            <div class="field quarter">    
                {!! Form::label('fechaFinal', 'Fecha fin: ') !!}         	
                {!! Form::date('fechaFinal', \Carbon\Carbon::now(), ['id' => 'datepicker','class' => 'form-control', 'placeholder' =>'Ejemplo: 30-03-2000', 'step'=>'1']) !!}
            </div>
        </div>
        <p></p>
        {!! Form::submit('Exporta todas las asignaciones de zonas geográficas *xls',['class' => 'button']) !!}
        {!! Form::close()!!}
        <p></p>
        <!-- Tabla -->
        <h2>Tabla de Asignación Zonas Geográficas</h2>
        {!! Form::open(['url' => 'main/zonageo/asigadministrar/borra', 'method' => 'post']) !!}
        <p></p>
		<!--Tabla de ocurrencias de zonas geográficas -->
        <table class="table" align="center" size="small">
                <thead>
                    <th>Operación</th>
                    <th align="center">Check</th>
                    <th>RUT</th>
                    <th>Alias  zona<br/>geográfica</th>
                    <th>Tipo marca</th>
                    <th>Fecha Inicial</th>
                    <th>Fecha Final</th>
                </thead>
            @foreach($asigzonageos as $asigzonageo) 
                <tbody>
                    <td>{!! link_to_route('main.zonageo.asigadministrar.edit', $title = 'Modificar', $parameters = $asigzonageo->contador, $attributes = ['class'=>'btn btn-primary']) !!}</td>
                    <td align="center"><input id="{{$asigzonageo->contador}}" value="{{$asigzonageo->contador}}" name="delete[]" type="checkbox" class="checkthis"/><label for="{{$asigzonageo->contador}}"></label></td>
                    <td>{{$asigzonageo->RUT}}</td>
                    <td>{{$asigzonageo->Alias_loc_geo}}</td>
                    <td>{{$asigzonageo->Tipo_marca}}</td>
                    <td>{{ date('d-m-Y',strtotime($asigzonageo->Fecha_inicio)) }}</td>
                    <td>{{ date('d-m-Y',strtotime($asigzonageo->Fecha_fin)) }}</td>
                </tbody>
            @endforeach
        </table>
    {!! $asigzonageos->render()!!}
    <p></p>
    <!-- Eliminación masiva -->
    {!! Form::submit('Eliminar check de asociaciones',['class' => 'button small']) !!}
    {!! Form::close() !!}	    	
@stop            

@section('submenu')
@include('menus.zonageo')
@stop             

@section('subseccion11')
@include('menus.menus_ayuda')
@stop    

resources/views/sistema/zonageo/nuevo.blade.php
@extends('layouts.principal')

@section('bienvenida')
    <h1>Zonas Geográficas</h1>
    <p>Bienvenidos a Asistance</p>
	<p>Por favor, complete el formulario.</p>
	
	@include('alertas.alerta')
	@include('alertas.validaformulario')
	<section>
			{!! Form::open(['route' => 'main.zonageo.administrar.store', 'method' => 'POST']) !!}
				<div class="fields">
					<div class="field">
					{!! Form::label('Alias_loc_geo', 'Alias o pseudónimo: ') !!}
					{!! Form::text('Alias_loc_geo', null, ['class' => 'form-control', 'maxlength' => '24', 'placeholder' =>'Ejemplo: ZONAGEO-0001']) !!}
					</div>
					<h4>Arrastre los marcadores del mapa para captuar ambos puntos del área geográfica a establecer</h4>
					<h5>La fecha azul debe ubicarse en la zona inferior izquierda del mapa. </h5><br>
					<h5> La fecha roja debe ubicarse en la zona superior derecha del mapa. </h5><br>
					<h4>No olvide aceptar que Google permita detectar su posición actual. </h4><br />
					<div class="field" id="map"style="width: 800px; height:600px;"><br /></div>
					<div class="field half">
						{!! Form::label('coorX1', 'Componente X primer vértice superior izquierdo: ') !!}
						<input type="text" name="coorX1" id="long1" readonly="readonly" />
						{!! Form::label('coorY1', 'Componente Y primer vértice superior izquierdo: ') !!}
						<input type="text" name="coorY1" id="lat1" readonly="readonly" />
					</div>
					<div class="field half">
						{!! Form::label('coorX2', 'Componente X segundo vértice superior izquierdo: ') !!}
						<input type="text" name="coorX2" id="long2" readonly="readonly" />
						{!! Form::label('coorY2', 'Componente Y segundo vértice superior izquierdo: ') !!}
						<input type="text" name="coorY2" id="lat2" readonly="readonly" />
					</div>
				</div>
                <ul class="actions">
					<li>
						{!! Form::submit('Generar nueva zona',['class' => 'btn btn-primary']) !!}
					</li>
                </ul>
			{!! Form::close() !!}
		</section>
		<script src="{{ URL::asset('assets/js/locgeo.js')}}"></script>
@stop         

@section('submenu')
@include('menus.zonageo')
@stop         

@section('subseccion11')
@include('menus.menus_ayuda') 
<!-- La clave de API acá la obtuve de cuenta Google Cloud: AIzaSyBz2P8cnKkLgEjK2h2C1dtfD8B8gRmEARI --> 
<script async defer src="https://maps.googleapis.com/maps/api/js?key=
AIzaSyBz2P8cnKkLgEjK2h2C1dtfD8B8gRmEARI&callback=initMap"
type="text/javascript"></script>
@stop 